<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# Amigos',
    '# Mtgs' => 'Montanhas',
    '# Mtgs L30' => '# Mtgs L30',
    '# Places' => '# Locais',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcpnt L30',
    '#FB' => '#FB',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => 'Reunião% Created',
    '% Created Meeting Last30' => '% Criado Reunião Last30',
    '% Invited & Created Meeting' => '% Reunião convidada e criada',
    '%Prtcpnt' => '% Prtcpnt',
    '%Prtcpnt L30' => '% Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'Uma versão de teste foi enviada aos administradores.',
    'Action Text' => 'Texto da ação',
    'Action Url' => 'URL de ação',
    'Are you sure you want to delete this item?' => 'Tem certeza de que deseja excluir este item?',
    'Caption' => 'Rubrica',
    'Content' => 'Conteúdo',
    'Create' => 'Crio',
    'Create Historical Data' => 'Criar dados históricos',
    'Create Launch' => 'Criar lançamento',
    'Create Message' => 'Criar mensagem',
    'Create Message Log' => 'Criar registro de mensagens',
    'Create Place' => 'Criar lugar',
    'Create User' => 'Criar Usuário',
    'Create User Data' => 'Criar dados de usuário',
    'Created At' => 'Criado em',
    'Date' => 'Encontro',
    'Delete' => 'Excluir',
    'Domain' => 'Domínio',
    'Ext' => 'Ext',
    'Frnds/Usr' => 'Frnds / Usr',
    'Historical Datas' => 'Dados históricos',
    'Historical Statistics' => 'Estatísticas históricas',
    'ID' => 'identidade',
    'Inv>Org' => 'Inv> Org',
    'Is Social?' => 'É Social?',
    'Launches' => 'Lança',
    'Level' => 'Nível',
    'Meeting Planner' => 'Planejador de reuniões',
    'Message ID' => 'ID da mensagem',
    'Message Logs' => 'Registros de Mensagens',
    'Messages' => 'Mensagens',
    'Mtgs/Usr' => 'Mtgs / Usr',
    'Places' => 'Locais',
    'Plcs/Usr' => 'Plcs / Usr',
    'Reset' => 'Restabelecer',
    'Response' => 'Resposta',
    'Search' => 'Pesquisa',
    'Sorry, we had a problem deleting your message.' => 'Lamentamos, mas tivemos um problema ao eliminar a sua mensagem.',
    'Status' => 'Status',
    'Subject' => 'Sujeito',
    'Target' => 'Alvo',
    'This message has been sent.' => 'Esta mensagem foi enviada.',
    'UId' => 'UId',
    'Update' => 'Atualizar',
    'Update {modelClass}: ' => 'Atualizar {modelClass} :',
    'Updated At' => 'Atualizado em',
    'User Data as of Yesterday' => 'Dados do usuário desde ontem',
    'User Datas' => 'Dados do usuário',
    'User ID' => 'ID do usuário',
    'Users' => 'Comercial',
    'Your contacts have been imported.' => 'Seus contatos foram importados.',
    'Your message has been deleted.' => 'Sua mensagem foi excluída.',
    'error!' => 'erro!',
    'ok' => 'Está bem',
    'one or more meetings not cleared_at in 24 hours' => 'Uma ou mais reuniões não autorizadas em 24 horas',
    'ten recent meetings cleared_at = 0' => 'Dez reuniões recentes cleared_at = 0',
    'warn' => 'advertir',
];