<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<Strong> Observação: </ strong> Use um navegador atualizado para ver os comentários.',
    'Download' => 'Transferir',
    'Follow' => 'Segue',
    'Fork' => 'Garfo',
    'Issue' => 'Questão',
    'Login with Facebook' => 'Entrar com o Facebook',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Ative o JavaScript no seu navegador para visualizar o Facebook {pluginName} Plugin corretamente neste site.',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Ative o JavaScript no seu navegador para exibir o Google {pluginName} Plugin corretamente neste site.',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'Ative o JavaScript no seu navegador para ver o Twitter {pluginName} Plugin corretamente neste site.',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'Ative o JavaScript no seu navegador para exibir o VKontakte {pluginName} Plugin corretamente neste site.',
    'Please enable JavaScript to view the {pluginLink}.' => 'Ative o JavaScript para visualizar o {pluginLink} .',
    'Star' => 'Estrela',
    'Watch' => 'Assistir',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'Você deve habilitar Javascript no seu navegador para que o site funcione de forma otimizada e exiba seções completamente.',
    'comments powered by Disqus' => 'Comentários alimentados por Disqus',
];