<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Are you sure you want to delete this item?' => 'آیا مطمئن هستید که میخواهید این مورد را حذف کنید؟',
    'Create' => 'ايجاد كردن',
    'Create User' => 'ایجاد کاربر',
    'Created At' => 'ایجاد شده در',
    'Delete' => 'حذف',
    'ID' => 'شناسه',
    'Reset' => 'تنظیم مجدد',
    'Search' => 'جستجو کردن',
    'Token' => 'رمز',
    'Update' => 'به روز رسانی',
    'Update {modelClass}: ' => 'به روز رسانی {modelClass} :',
    'Updated At' => 'به روز شده در',
    'User ID' => 'شناسه کاربر',
    'Users' => 'کاربران',
];