<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# دوستان',
    '# Mtgs' => '# Mtgs',
    '# Mtgs L30' => '# Mtgs L30',
    '# Places' => '# اماکن',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcpnt L30',
    '#FB' => '#FB',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '٪ نشست ایجاد شده',
    '% Created Meeting Last30' => '٪ ایجاد نشست Last30',
    '% Invited & Created Meeting' => '٪ دعوت و ایجاد نشست',
    '%Prtcpnt' => '٪ Prtcpnt',
    '%Prtcpnt L30' => '٪ Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'یک نسخه آزمایشی از این به مدیران ارسال می شود.',
    'Action Text' => 'اقدام متن',
    'Action Url' => 'اقدام آدرس',
    'Are you sure you want to delete this item?' => 'آیا مطمئن هستید که میخواهید این مورد را حذف کنید؟',
    'Caption' => 'عنوان',
    'Content' => 'محتوا',
    'Create' => 'ايجاد كردن',
    'Create Historical Data' => 'درست داده های تاریخی',
    'Create Launch' => 'درست راه اندازی',
    'Create Message' => 'ایجاد پیام',
    'Create Message Log' => 'درست پیام ورود',
    'Create Place' => 'ایجاد محل',
    'Create User' => 'ایجاد کاربر',
    'Create User Data' => 'درست داده های کاربر',
    'Created At' => 'ایجاد شده در',
    'Date' => 'تاریخ',
    'Delete' => 'حذف',
    'Domain' => 'دامنه',
    'Ext' => 'فریم ورک Ext',
    'Frnds/Usr' => 'Frnds مسیر / usr',
    'Historical Datas' => 'دادهها تاریخی',
    'Historical Statistics' => 'آمار تاریخی',
    'ID' => 'شناسه',
    'Inv>Org' => 'INV> سازمان',
    'Is Social?' => 'است اجتماعی؟',
    'Launches' => 'قایق',
    'Level' => 'سطح',
    'Meeting Planner' => 'برنامه ریز ملاقات',
    'Message ID' => 'شماره پیام',
    'Message Logs' => 'گزارش ها پیام',
    'Messages' => 'پیام',
    'Mtgs/Usr' => 'Mtgs مسیر / usr',
    'Places' => 'اماکن',
    'Plcs/Usr' => 'PLC ها از / usr',
    'Reset' => 'تنظیم مجدد',
    'Response' => 'واکنش',
    'Search' => 'جستجو کردن',
    'Sorry, we had a problem deleting your message.' => 'با عرض پوزش، ما یک مشکل حذف پیام خود را داشته است.',
    'Status' => 'وضعیت',
    'Subject' => 'موضوع',
    'Target' => 'هدف',
    'This message has been sent.' => 'این پیام ارسال شده است.',
    'UId' => 'UID',
    'Update' => 'به روز رسانی',
    'Update {modelClass}: ' => 'به روز رسانی {modelClass} :',
    'Updated At' => 'به روز شده در',
    'User Data as of Yesterday' => 'اطلاعات کاربر از دیروز',
    'User Datas' => 'دادهها کاربر',
    'User ID' => 'شناسه کاربر',
    'Users' => 'کاربران',
    'Your contacts have been imported.' => 'اطلاعات تماس شما وارد شده است.',
    'Your message has been deleted.' => 'پیام شما حذف شده است.',
    'error!' => 'خطا!',
    'ok' => 'خوب',
    'one or more meetings not cleared_at in 24 hours' => 'یک یا چند جلسه در 24 ساعت cleared_at نیست',
    'ten recent meetings cleared_at = 0' => 'ده جلسات اخیر cleared_at = 0',
    'warn' => 'هشدار دادن',
];