<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<strong> توجه: </ strong> لطفا یک مرورگر به روز شده برای مشاهده نظرات استفاده کنید.',
    'Download' => 'دانلود',
    'Follow' => 'دنبال کردن',
    'Fork' => 'چنگال',
    'Issue' => 'موضوع',
    'Login with Facebook' => 'برای ورود با فیس بوک',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'لطفا جاوا اسکریپت را در مرورگر خود فعال برای مشاهده فیس بوک {pluginName} پلاگین به درستی در این سایت.',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'لطفا جاوا اسکریپت را در مرورگر خود فعال برای مشاهده گوگل {pluginName} پلاگین به درستی در این سایت.',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'لطفا جاوا اسکریپت را در مرورگر خود فعال برای مشاهده توییتر {pluginName} پلاگین به درستی در این سایت.',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'لطفا جاوا اسکریپت را در مرورگر خود فعال برای مشاهده VKontakte می {pluginName} پلاگین به درستی در این سایت.',
    'Please enable JavaScript to view the {pluginLink}.' => 'لطفا جاوا اسکریپت را فعال برای مشاهده {pluginLink} .',
    'Star' => 'ستاره',
    'Watch' => 'تماشا کردن',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'شما باید جاوا اسکریپت را در مرورگر خود فعال برای سایت به کار بهینه و نمایش بخش به طور کامل.',
    'comments powered by Disqus' => 'نظر توسط Disqus',
];