<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# Vrienden',
    '# Mtgs' => '# Mtgs',
    '# Mtgs L30' => '# Mtgs L30',
    '# Places' => '# Plaatsen',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcnt L30',
    '#FB' => '#fb',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '% Gecreëerde vergadering',
    '% Created Meeting Last30' => '% Gecreëerde vergadering Last30',
    '% Invited & Created Meeting' => '% Uitgenodigd & Gecreëerd Meeting',
    '%Prtcpnt' => '% Prtcpnt',
    '%Prtcpnt L30' => '% Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'Een testversie hiervan is naar beheerders gestuurd.',
    'Action Text' => 'Actie Tekst',
    'Action Url' => 'Actie Url',
    'Are you sure you want to delete this item?' => 'Weet u zeker dat u dit item wilt verwijderen?',
    'Caption' => 'Onderschrift',
    'Content' => 'Inhoud',
    'Create' => 'creëren',
    'Create Historical Data' => 'Historische gegevens maken',
    'Create Launch' => 'Launch starten',
    'Create Message' => 'Creeër bericht',
    'Create Message Log' => 'Maak een bericht aan',
    'Create Place' => 'Plaats creëren',
    'Create User' => 'Gebruikers maken',
    'Create User Data' => 'Gebruikersgegevens maken',
    'Created At' => 'Gemaakt bij',
    'Date' => 'Datum',
    'Delete' => 'Verwijder',
    'Domain' => 'Domein',
    'Ext' => 'Ext',
    'Frnds/Usr' => 'Frnds / Usr',
    'Historical Datas' => 'Historische data',
    'Historical Statistics' => 'Historische Statistieken',
    'ID' => 'ID kaart',
    'Inv>Org' => 'Inv> Org',
    'Is Social?' => 'Is sociaal?',
    'Launches' => 'lanceringen',
    'Level' => 'Niveau',
    'Meeting Planner' => 'Vergaderplanner',
    'Message ID' => 'Bericht-ID',
    'Message Logs' => 'Berichtlogboeken',
    'Messages' => 'berichten',
    'Mtgs/Usr' => 'Mtgs / Usr',
    'Places' => 'plaatsen',
    'Plcs/Usr' => 'Plcs / Usr',
    'Reset' => 'Reset',
    'Response' => 'antwoord',
    'Search' => 'Zoeken',
    'Sorry, we had a problem deleting your message.' => 'Sorry, we hebben een probleem gehad met het verwijderen van uw bericht.',
    'Status' => 'staat',
    'Subject' => 'Onderwerpen',
    'Target' => 'Doel',
    'This message has been sent.' => 'Dit bericht is verzonden.',
    'UId' => 'uid',
    'Update' => 'Bijwerken',
    'Update {modelClass}: ' => 'Bijwerken {modelClass} :',
    'Updated At' => 'Bijgewerkt bij',
    'User Data as of Yesterday' => 'Gebruikersgegevens vanaf gisteren',
    'User Datas' => 'Gebruikersgegevens',
    'User ID' => 'gebruikersnaam',
    'Users' => 'gebruikers',
    'Your contacts have been imported.' => 'Uw contacten zijn geïmporteerd.',
    'Your message has been deleted.' => 'Uw bericht is verwijderd.',
    'error!' => 'fout!',
    'ok' => 'OK',
    'one or more meetings not cleared_at in 24 hours' => 'Één of meer vergaderingen die niet binnen 24 uur worden gewist',
    'ten recent meetings cleared_at = 0' => 'Tien recente vergaderingen cleared_at = 0',
    'warn' => 'waarschuwen',
];