<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<Strong> Opmerking: </ strong> Gebruik een geupdateerde browser om reacties te bekijken.',
    'Download' => 'Download',
    'Follow' => 'Volgen',
    'Fork' => 'Vork',
    'Issue' => 'Kwestie',
    'Login with Facebook' => 'Inloggen met Facebook',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Activeer JavaScript op uw browser om de Facebook te bekijken {pluginName} Plug-in correct op deze site.',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Activeer JavaScript op uw browser om de Google te bekijken {pluginName} Plug-in correct op deze site.',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'Activeer JavaScript op uw browser om de Twitter te bekijken {pluginName} Plug-in correct op deze site.',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'Activeer JavaScript op uw browser om de VKontakte te bekijken {pluginName} Plug-in correct op deze site.',
    'Please enable JavaScript to view the {pluginLink}.' => 'Activeer JavaScript alsjeblieft om de {pluginLink} .',
    'Star' => 'Ster',
    'Watch' => 'Kijk maar',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'U moet Javascript op uw browser inschakelen voor de site optimaal werken en secties volledig weergeven.',
    'comments powered by Disqus' => 'Opmerkingen powered by Disqus',
];