<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# Vänner',
    '# Mtgs' => '# Mtgs',
    '# Mtgs L30' => '# Mtgs L30',
    '# Places' => '# Platser',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcpnt L30',
    '#FB' => '#fb',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '% Skapat möte',
    '% Created Meeting Last30' => '% Skapad möte Last30',
    '% Invited & Created Meeting' => '% Inbjudna och skapade möte',
    '%Prtcpnt' => '% Prtcpnt',
    '%Prtcpnt L30' => '% Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'En testversion av detta har skickats till administratörer.',
    'Action Text' => 'Action Text',
    'Action Url' => 'Åtgärd Url',
    'Are you sure you want to delete this item?' => 'Är du säker på att du vill radera detta föremål?',
    'Caption' => 'Rubrik',
    'Content' => 'Innehåll',
    'Create' => 'Skapa',
    'Create Historical Data' => 'Skapa historiska data',
    'Create Launch' => 'Skapa start',
    'Create Message' => 'Skapa meddelande',
    'Create Message Log' => 'Skapa meddelandeloggen',
    'Create Place' => 'Skapa plats',
    'Create User' => 'Skapa användare',
    'Create User Data' => 'Skapa användardata',
    'Created At' => 'Skapat på',
    'Date' => 'Datum',
    'Delete' => 'Radera',
    'Domain' => 'Domän',
    'Ext' => 'Ext',
    'Frnds/Usr' => 'Frnds / usr',
    'Historical Datas' => 'Historiska data',
    'Historical Statistics' => 'Historisk statistik',
    'ID' => 'ID',
    'Inv>Org' => 'Inv> Org',
    'Is Social?' => 'Är socialt?',
    'Launches' => 'lanseringar',
    'Level' => 'Nivå',
    'Meeting Planner' => 'Mötesplanerare',
    'Message ID' => 'Meddelande-ID',
    'Message Logs' => 'Meddelande loggar',
    'Messages' => 'meddelanden',
    'Mtgs/Usr' => 'MTGs / usr',
    'Places' => 'platser',
    'Plcs/Usr' => 'PLC / usr',
    'Reset' => 'Återställa',
    'Response' => 'Svar',
    'Search' => 'Sök',
    'Sorry, we had a problem deleting your message.' => 'Tyvärr, vi hade ett problem att radera ditt meddelande.',
    'Status' => 'Status',
    'Subject' => 'Ämne',
    'Target' => 'Mål',
    'This message has been sent.' => 'Detta meddelande har skickats.',
    'UId' => 'uid',
    'Update' => 'Uppdatering',
    'Update {modelClass}: ' => 'Uppdatering {modelClass} :',
    'Updated At' => 'Uppdaterad på',
    'User Data as of Yesterday' => 'Användardata från och med igår',
    'User Datas' => 'Användardata',
    'User ID' => 'användar ID',
    'Users' => 'användare',
    'Your contacts have been imported.' => 'Dina kontakter har importerats.',
    'Your message has been deleted.' => 'Ditt meddelande har tagits bort.',
    'error!' => 'fel!',
    'ok' => 'ok',
    'one or more meetings not cleared_at in 24 hours' => 'Ett eller flera möten inte cleared_at om 24 timmar',
    'ten recent meetings cleared_at = 0' => 'Tio senaste möten cleared_at = 0',
    'warn' => 'varna',
];