<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<Strong> Obs! </ Strong> Vänligen använd en uppdaterad webbläsare för att visa kommentarer.',
    'Download' => 'Ladda ner',
    'Follow' => 'Följ',
    'Fork' => 'Gaffel',
    'Issue' => 'Problem',
    'Login with Facebook' => 'Logga in med Facebook',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Aktivera JavaScript i din webbläsare för att se Facebook {pluginName} Plugin korrekt på den här webbplatsen.',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Aktivera JavaScript i din webbläsare för att se Google {pluginName} Plugin korrekt på den här webbplatsen.',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'Vänligen aktivera JavaScript i din webbläsare för att se Twitter {pluginName} Plugin korrekt på den här webbplatsen.',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'Vänligen aktivera JavaScript i din webbläsare för att se VKontakte {pluginName} Plugin korrekt på den här webbplatsen.',
    'Please enable JavaScript to view the {pluginLink}.' => 'Vänligen aktivera JavaScript för att visa {pluginLink} .',
    'Star' => 'Stjärna',
    'Watch' => 'Kolla på',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'Du måste aktivera Javascript på din webbläsare för att webbplatsen ska fungera optimalt och visa sektioner helt.',
    'comments powered by Disqus' => 'Kommentarer powered by Disqus',
];