<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# เพื่อน',
    '# Mtgs' => '# Mtgs',
    '# Mtgs L30' => '# Mtgs L30',
    '# Places' => '# Places',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcpnt L30',
    '#FB' => '#FB',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => 'สร้างการประชุม',
    '% Created Meeting Last30' => 'สร้างการประชุม Last30',
    '% Invited & Created Meeting' => '% เชิญและสร้างการประชุม',
    '%Prtcpnt' => '% Prtcpnt',
    '%Prtcpnt L30' => '% Prtcpnt',
    'A test version of this has been sent to administrators.' => 'มีการส่งเวอร์ชันทดสอบไปยังผู้ดูแลระบบแล้ว',
    'Action Text' => 'ข้อความ Action',
    'Action Url' => 'Url การกระทำ',
    'Are you sure you want to delete this item?' => 'คุณแน่ใจหรือว่าต้องการลบรายการนี้หรือไม่?',
    'Caption' => 'คำบรรยายภาพ',
    'Content' => 'เนื้อหา',
    'Create' => 'สร้าง',
    'Create Historical Data' => 'สร้างข้อมูลทางประวัติศาสตร์',
    'Create Launch' => 'สร้าง Launch',
    'Create Message' => 'สร้างข้อความ',
    'Create Message Log' => 'สร้างบันทึกข้อความ',
    'Create Place' => 'สร้าง Place',
    'Create User' => 'สร้างผู้ใช้',
    'Create User Data' => 'สร้างข้อมูลผู้ใช้',
    'Created At' => 'สร้างเมื่อ',
    'Date' => 'วันที่',
    'Delete' => 'ลบ',
    'Domain' => 'โดเมน',
    'Ext' => 'ext',
    'Frnds/Usr' => 'frnds นี้ / usr',
    'Historical Datas' => 'ข้อมูลทางประวัติศาสตร์',
    'Historical Statistics' => 'สถิติทางประวัติศาสตร์',
    'ID' => 'ID',
    'Inv>Org' => 'Inv> องค์กร',
    'Is Social?' => 'เป็นสังคมหรือไม่?',
    'Launches' => 'เปิดตัว',
    'Level' => 'ชั้น',
    'Meeting Planner' => 'วางแผนการประชุม',
    'Message ID' => 'รหัสข้อความ',
    'Message Logs' => 'บันทึกข้อความ',
    'Messages' => 'ข้อความ',
    'Mtgs/Usr' => 'MTGS นี้ / usr',
    'Places' => 'สถานที่',
    'Plcs/Usr' => 'PLCs นี้ / usr',
    'Reset' => 'รีเซ็ต',
    'Response' => 'คำตอบ',
    'Search' => 'ค้นหา',
    'Sorry, we had a problem deleting your message.' => 'ขออภัยเรามีปัญหาในการลบข้อความของคุณ',
    'Status' => 'สถานะ',
    'Subject' => 'เรื่อง',
    'Target' => 'เป้า',
    'This message has been sent.' => 'ข้อความนี้ถูกส่งแล้ว',
    'UId' => 'UID',
    'Update' => 'ปรับปรุง',
    'Update {modelClass}: ' => 'ปรับปรุง {modelClass} :',
    'Updated At' => 'อัปเดตที่',
    'User Data as of Yesterday' => 'ข้อมูลผู้ใช้ตั้งแต่วันนี้',
    'User Datas' => 'Datas ผู้ใช้',
    'User ID' => 'User ID',
    'Users' => 'ผู้ใช้',
    'Your contacts have been imported.' => 'ระบบนำเข้าที่อยู่ติดต่อของคุณแล้ว',
    'Your message has been deleted.' => 'ข้อความของคุณถูกลบแล้ว',
    'error!' => 'ข้อผิดพลาด!',
    'ok' => 'ตกลง',
    'one or more meetings not cleared_at in 24 hours' => 'การประชุมหนึ่งครั้งหรือมากกว่านั้นไม่ได้รับการหักล้างใน 24 ชั่วโมง',
    'ten recent meetings cleared_at = 0' => 'การประชุมล่าสุด 10 ครั้ง clear_at = 0',
    'warn' => 'เตือน',
];