<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<strong> หมายเหตุ: </ strong> โปรดใช้เบราว์เซอร์ที่ได้รับการอัปเดตเพื่อดูความคิดเห็น',
    'Download' => 'ดาวน์โหลด',
    'Follow' => 'ปฏิบัติตาม',
    'Fork' => 'ส้อม',
    'Issue' => 'ปัญหา',
    'Login with Facebook' => 'เข้าสู่ระบบด้วย Facebook',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'โปรดเปิดใช้งาน JavaScript ในเบราว์เซอร์ของคุณเพื่อดู Facebook {pluginName} ปลั๊กอินได้อย่างถูกต้องบนไซต์นี้',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'โปรดเปิดใช้งาน JavaScript ในเบราว์เซอร์ของคุณเพื่อดู Google {pluginName} ปลั๊กอินได้อย่างถูกต้องบนไซต์นี้',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'โปรดเปิดใช้งาน JavaScript ในเบราว์เซอร์ของคุณเพื่อดู Twitter {pluginName} ปลั๊กอินได้อย่างถูกต้องบนไซต์นี้',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'โปรดเปิดใช้งาน JavaScript ในเบราว์เซอร์ของคุณเพื่อดู VKontakte {pluginName} ปลั๊กอินได้อย่างถูกต้องบนไซต์นี้',
    'Please enable JavaScript to view the {pluginLink}.' => 'โปรดเปิดใช้งาน JavaScript เพื่อดู {pluginLink} .',
    'Star' => 'ดาว',
    'Watch' => 'ดู',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'คุณต้องเปิดใช้งาน Javascript ในเบราว์เซอร์ของคุณเพื่อให้ไซต์ทำงานได้ดีที่สุดและแสดงส่วนต่างๆทั้งหมด',
    'comments powered by Disqus' => 'ความคิดเห็นขับเคลื่อนโดย Disqus',
];