<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Are you sure you want to delete this item?' => 'このアイテムを削除してもよろしいですか？',
    'Create' => '作成する',
    'Create User' => 'ユーザーの作成',
    'Created At' => '作成者：',
    'Delete' => '削除',
    'ID' => 'ID',
    'Reset' => 'リセット',
    'Search' => 'サーチ',
    'Token' => 'トークン',
    'Update' => '更新',
    'Update {modelClass}: ' => '更新 {modelClass} ：',
    'Updated At' => '更新日',
    'User ID' => 'ユーザーID',
    'Users' => 'ユーザー',
];