<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '＃友達',
    '# Mtgs' => '＃Mtgs',
    '# Mtgs L30' => '＃Mtgs L30',
    '# Places' => '＃場所',
    '# Prtcpnt' => '＃Prtcpnt',
    '# Prtcpnt L30' => '＃Prtcpnt L30',
    '#FB' => '#FB',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '作成された会議の割合',
    '% Created Meeting Last30' => '作成された会議の最終日の％30',
    '% Invited & Created Meeting' => '招待された招待された会議の％',
    '%Prtcpnt' => '％Prtcpnt',
    '%Prtcpnt L30' => '％Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'このテスト版が管理者に送信されました。',
    'Action Text' => 'アクションテキスト',
    'Action Url' => 'アクションURL',
    'Are you sure you want to delete this item?' => 'このアイテムを削除してもよろしいですか？',
    'Caption' => 'キャプション',
    'Content' => 'コンテンツ',
    'Create' => '作成する',
    'Create Historical Data' => '履歴データの作成',
    'Create Launch' => '起動を作成する',
    'Create Message' => 'メッセージを作成',
    'Create Message Log' => 'メッセージログの作成',
    'Create Place' => '場所を作成する',
    'Create User' => 'ユーザーの作成',
    'Create User Data' => 'ユーザーデータの作成',
    'Created At' => '作成者：',
    'Date' => '日付',
    'Delete' => '削除',
    'Domain' => 'ドメイン',
    'Ext' => 'Ext',
    'Frnds/Usr' => 'Frnds / Usr',
    'Historical Datas' => '歴史的データ',
    'Historical Statistics' => '歴史的統計',
    'ID' => 'ID',
    'Inv>Org' => 'Inv>組織',
    'Is Social?' => '社会は？',
    'Launches' => '打ち上げ',
    'Level' => 'レベル',
    'Meeting Planner' => 'ミーティングプランナー',
    'Message ID' => 'メッセージID',
    'Message Logs' => 'メッセージログ',
    'Messages' => 'メッセージ',
    'Mtgs/Usr' => 'Mtgs / Usr',
    'Places' => '場所',
    'Plcs/Usr' => 'Plcs / Usr',
    'Reset' => 'リセット',
    'Response' => '応答',
    'Search' => 'サーチ',
    'Sorry, we had a problem deleting your message.' => 'メッセージを削除する際に問題が発生しました。',
    'Status' => '状態',
    'Subject' => '件名',
    'Target' => 'ターゲット',
    'This message has been sent.' => 'このメッセージは送信されました。',
    'UId' => 'UId',
    'Update' => '更新',
    'Update {modelClass}: ' => '更新 {modelClass} ：',
    'Updated At' => '更新日',
    'User Data as of Yesterday' => '昨日のユーザーデータ',
    'User Datas' => 'ユーザーデータ',
    'User ID' => 'ユーザーID',
    'Users' => 'ユーザー',
    'Your contacts have been imported.' => 'あなたの連絡先がインポートされました。',
    'Your message has been deleted.' => 'あなたのメッセージは削除されました。',
    'error!' => 'エラー！',
    'ok' => 'OK',
    'one or more meetings not cleared_at in 24 hours' => '24時間以内にcleared_atしていない1つまたは複数の会議',
    'ten recent meetings cleared_at = 0' => '最近の10回の会議cleared_at = 0',
    'warn' => '警告する',
];