<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<strong>注：</ strong>コメントを表示するには、更新されたブラウザを使用してください。',
    'Download' => 'ダウンロード',
    'Follow' => 'フォローする',
    'Fork' => 'フォーク',
    'Issue' => '問題',
    'Login with Facebook' => 'Facebookでログイン',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Facebookを表示するには、ブラウザでJavaScriptを有効にしてください {pluginName} このサイトでは正しくプラグインされています。',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Googleを表示するには、ブラウザでJavaScriptを有効にしてください {pluginName} このサイトでは正しくプラグインされています。',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'Twitterを表示するには、ブラウザでJavaScriptを有効にしてください {pluginName} このサイトでは正しくプラグインされています。',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'VKontakteを表示するには、ブラウザでJavaScriptを有効にしてください {pluginName} このサイトでは正しくプラグインされています。',
    'Please enable JavaScript to view the {pluginLink}.' => 'JavaScriptを有効にしてください {pluginLink} 。',
    'Star' => '星',
    'Watch' => '時計',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'サイトが最適に動作し、セクションを完全に表示するには、ブラウザでJavascriptを有効にする必要があります。',
    'comments powered by Disqus' => 'Disqusによって供給されたコメント',
];