<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Are you sure you want to delete this item?' => '你确定要删除这个项目吗？',
    'Create' => '创建',
    'Create User' => '创建用户',
    'Created At' => '创建于',
    'Delete' => '删除',
    'ID' => 'ID',
    'Reset' => '重启',
    'Search' => '搜索',
    'Token' => '令牌',
    'Update' => '更新',
    'Update {modelClass}: ' => '更新 {modelClass} ：',
    'Updated At' => '更新于',
    'User ID' => '用户名',
    'Users' => '用户',
];