<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '＃朋友',
    '# Mtgs' => '＃Mtgs',
    '# Mtgs L30' => '＃Mtgs L30',
    '# Places' => '＃个地方',
    '# Prtcpnt' => '＃Prtcpnt',
    '# Prtcpnt L30' => '＃Prtcpnt L30',
    '#FB' => '#FB',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '创建会议％',
    '% Created Meeting Last30' => '％创建会议Last30',
    '% Invited & Created Meeting' => '％邀请和创建会议',
    '%Prtcpnt' => '％Prtcpnt',
    '%Prtcpnt L30' => '％Prtcpnt L30',
    'A test version of this has been sent to administrators.' => '此测试版本已发送给管理员。',
    'Action Text' => '行动文本',
    'Action Url' => '动作网址',
    'Are you sure you want to delete this item?' => '你确定要删除这个项目吗？',
    'Caption' => '标题',
    'Content' => '内容',
    'Create' => '创建',
    'Create Historical Data' => '创建历史数据',
    'Create Launch' => '创建启动',
    'Create Message' => '创建消息',
    'Create Message Log' => '创建消息日志',
    'Create Place' => '创建地点',
    'Create User' => '创建用户',
    'Create User Data' => '创建用户数据',
    'Created At' => '创建于',
    'Date' => '日期',
    'Delete' => '删除',
    'Domain' => '域',
    'Ext' => '分机',
    'Frnds/Usr' => 'Frnds / Usr',
    'Historical Datas' => '历史数据',
    'Historical Statistics' => '历史统计',
    'ID' => 'ID',
    'Inv>Org' => 'Inv>组织',
    'Is Social?' => '社会吗',
    'Launches' => '推出',
    'Level' => '水平',
    'Meeting Planner' => '会议策划',
    'Message ID' => '消息ID',
    'Message Logs' => '消息日志',
    'Messages' => '消息',
    'Mtgs/Usr' => 'Mtgs / Usr',
    'Places' => '地方',
    'Plcs/Usr' => 'Plcs / Usr',
    'Reset' => '重启',
    'Response' => '响应',
    'Search' => '搜索',
    'Sorry, we had a problem deleting your message.' => '抱歉，删除您的邮件时出现问题。',
    'Status' => '状态',
    'Subject' => '学科',
    'Target' => '目标',
    'This message has been sent.' => '此消息已发送。',
    'UId' => 'UId',
    'Update' => '更新',
    'Update {modelClass}: ' => '更新 {modelClass} ：',
    'Updated At' => '更新于',
    'User Data as of Yesterday' => '截至昨天的用户数据',
    'User Datas' => '用户数据',
    'User ID' => '用户名',
    'Users' => '用户',
    'Your contacts have been imported.' => '您的联系人已导入。',
    'Your message has been deleted.' => '您的消息已被删除。',
    'error!' => '错误！',
    'ok' => '好',
    'one or more meetings not cleared_at in 24 hours' => '一个或多个会议在24小时内未被清除',
    'ten recent meetings cleared_at = 0' => '最近十次会议clear_at = 0',
    'warn' => '警告',
];