<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<strong>注意：</ strong>请使用更新的浏览器查看评论。',
    'Download' => '下载',
    'Follow' => '跟随',
    'Fork' => '叉子',
    'Issue' => '问题',
    'Login with Facebook' => '用Facebook登录',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => '请在您的浏览器上启用JavaScript以查看Facebook {pluginName} 插件在这个网站上正确。',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => '请在您的浏览器上启用JavaScript以查看Google {pluginName} 插件在这个网站上正确。',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => '请在您的浏览器上启用JavaScript以查看Twitter {pluginName} 插件在这个网站上正确。',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => '请在您的浏览器上启用JavaScript以查看VKontakte {pluginName} 插件在这个网站上正确。',
    'Please enable JavaScript to view the {pluginLink}.' => '请启用JavaScript以查看 {pluginLink} 。',
    'Star' => '星',
    'Watch' => '看',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => '您必须在浏览器上启用Javascript才能使网站最佳地工作并完全显示部分。',
    'comments powered by Disqus' => '评论由Disqus提供支持',
];