<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# Copains',
    '# Mtgs' => '# Mtgs',
    '# Mtgs L30' => '# Mtgs L30',
    '# Places' => '# Des endroits',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcpnt L30',
    '#FB' => '#FB',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#Plan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '% Réunion créée',
    '% Created Meeting Last30' => '% Créé une réunion dernière30',
    '% Invited & Created Meeting' => '% Réunion invitée et créée',
    '%Prtcpnt' => '% Prtcpnt',
    '%Prtcpnt L30' => '% Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'Une version de test a été envoyée aux administrateurs.',
    'Action Text' => 'Texte d\'action',
    'Action Url' => 'Url d\'action',
    'Are you sure you want to delete this item?' => 'Êtes-vous sûr de bien vouloir supprimer cet élément?',
    'Caption' => 'Légende',
    'Content' => 'Contenu',
    'Create' => 'Créer',
    'Create Historical Data' => 'Créer des données historiques',
    'Create Launch' => 'Créer un lancement',
    'Create Message' => 'Créer un message',
    'Create Message Log' => 'Créer un journal des messages',
    'Create Place' => 'Créer un lieu',
    'Create User' => 'Créer un utilisateur',
    'Create User Data' => 'Créer des données utilisateur',
    'Created At' => 'Créé à',
    'Date' => 'Rendez-vous amoureux',
    'Delete' => 'Effacer',
    'Domain' => 'Domaine',
    'Ext' => 'Ext',
    'Frnds/Usr' => 'Frnds / Usr',
    'Historical Datas' => 'Données historiques',
    'Historical Statistics' => 'Statistiques historiques',
    'ID' => 'ID',
    'Inv>Org' => 'Inv> Org',
    'Is Social?' => 'Est-ce social?',
    'Launches' => 'Lancement',
    'Level' => 'Niveau',
    'Meeting Planner' => 'Planificateur de réunion',
    'Message ID' => 'ID du message',
    'Message Logs' => 'Journal des messages',
    'Messages' => 'Messages',
    'Mtgs/Usr' => 'Mtgs / Usr',
    'Places' => 'Des endroits',
    'Plcs/Usr' => 'Plcs / Usr',
    'Reset' => 'Réinitialiser',
    'Response' => 'Réponse',
    'Search' => 'Chercher',
    'Sorry, we had a problem deleting your message.' => 'Désolé, nous avons eu un problème pour supprimer votre message.',
    'Status' => 'Statut',
    'Subject' => 'Assujettir',
    'Target' => 'Cible',
    'This message has been sent.' => 'Ce message a été envoyé.',
    'UId' => 'UId',
    'Update' => 'Mettre à jour',
    'Update {modelClass}: ' => 'Mettre à jour {modelClass} :',
    'Updated At' => 'Mis à jour à',
    'User Data as of Yesterday' => 'Données utilisateur à partir d\'hier',
    'User Datas' => 'Données utilisateur',
    'User ID' => 'Identifiant d\'utilisateur',
    'Users' => 'Utilisateurs',
    'Your contacts have been imported.' => 'Vos contacts ont été importés.',
    'Your message has been deleted.' => 'Votre message a été supprimé.',
    'error!' => 'Erreur!',
    'ok' => 'D\'accord',
    'one or more meetings not cleared_at in 24 hours' => 'Une ou plusieurs réunions ne sont pas effacées dans 24 heures',
    'ten recent meetings cleared_at = 0' => 'Dix réunions récentes cleared_at = 0',
    'warn' => 'prévenir',
];