<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<Strong> Remarque: </ strong> Utilisez un navigateur mis à jour pour afficher les commentaires.',
    'Download' => 'Télécharger',
    'Follow' => 'Suivre',
    'Fork' => 'Fourchette',
    'Issue' => 'Problème',
    'Login with Facebook' => 'Se connecter avec Facebook',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Activez JavaScript sur votre navigateur pour afficher le Facebook {pluginName} Plug-in correctement sur ce site.',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Activez JavaScript sur votre navigateur pour afficher Google {pluginName} Plug-in correctement sur ce site.',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'Activez JavaScript sur votre navigateur pour voir le Twitter {pluginName} Plug-in correctement sur ce site.',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'Activez JavaScript sur votre navigateur pour afficher le VKontakte {pluginName} Plug-in correctement sur ce site.',
    'Please enable JavaScript to view the {pluginLink}.' => 'Veuillez activer JavaScript pour afficher le {pluginLink} .',
    'Star' => 'Étoile',
    'Watch' => 'Regarder',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'Vous devez activer Javascript sur votre navigateur pour que le site fonctionne de manière optimale et affiche complètement les sections.',
    'comments powered by Disqus' => 'Commentaires diffusés par Disqus',
];