<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# Teman',
    '# Mtgs' => '# Mtgs',
    '# Mtgs L30' => '# Mtgs L30',
    '# Places' => '# Tempat',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcpnt L30',
    '#FB' => '#FB',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '% Rapat yang Dibuat',
    '% Created Meeting Last30' => '% Dibuat Rapat Terakhir30',
    '% Invited & Created Meeting' => 'Rapat yang Diundang & Dibuat',
    '%Prtcpnt' => '% Prtcpnt',
    '%Prtcpnt L30' => '% Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'Versi uji coba ini telah dikirim ke administrator.',
    'Action Text' => 'Teks Tindakan',
    'Action Url' => 'Url Tindakan',
    'Are you sure you want to delete this item?' => 'Yakin ingin menghapus item ini?',
    'Caption' => 'Keterangan',
    'Content' => 'Konten',
    'Create' => 'Membuat',
    'Create Historical Data' => 'Buat Data Historis',
    'Create Launch' => 'Buat Peluncuran',
    'Create Message' => 'Menulis pesan',
    'Create Message Log' => 'Buat Log Pesan',
    'Create Place' => 'Buat Tempat',
    'Create User' => 'Buat pengguna',
    'Create User Data' => 'Buat Data Pengguna',
    'Created At' => 'Dibuat di',
    'Date' => 'Tanggal',
    'Delete' => 'Menghapus',
    'Domain' => 'Domain',
    'Ext' => 'Ext',
    'Frnds/Usr' => 'Frnds / Usr',
    'Historical Datas' => 'Data historis',
    'Historical Statistics' => 'Statistik sejarah',
    'ID' => 'ID',
    'Inv>Org' => 'Inv> Org',
    'Is Social?' => 'Apakah Sosial?',
    'Launches' => 'Luncurkan',
    'Level' => 'Tingkat',
    'Meeting Planner' => 'Perencana Pertemuan',
    'Message ID' => 'ID pesan',
    'Message Logs' => 'Pesan log',
    'Messages' => 'Pesan',
    'Mtgs/Usr' => 'Mtgs / Usr',
    'Places' => 'Tempat',
    'Plcs/Usr' => 'Plcs / Usr',
    'Reset' => 'Reset',
    'Response' => 'Tanggapan',
    'Search' => 'Pencarian',
    'Sorry, we had a problem deleting your message.' => 'Maaf, kami mengalami masalah saat menghapus pesan Anda.',
    'Status' => 'Status',
    'Subject' => 'Subyek',
    'Target' => 'Target',
    'This message has been sent.' => 'Pesan ini telah terkirim',
    'UId' => 'UId',
    'Update' => 'Memperbarui',
    'Update {modelClass}: ' => 'Memperbarui {modelClass} :',
    'Updated At' => 'Diperbarui pada',
    'User Data as of Yesterday' => 'Data Pengguna sampai dengan Kemarin',
    'User Datas' => 'User Datas',
    'User ID' => 'identitas pengguna',
    'Users' => 'Pengguna',
    'Your contacts have been imported.' => 'Kontak Anda telah diimpor.',
    'Your message has been deleted.' => 'Pesan anda telah dihapus',
    'error!' => 'kesalahan!',
    'ok' => 'baik',
    'one or more meetings not cleared_at in 24 hours' => 'Satu atau beberapa pertemuan tidak dibersihkan dalam 24 jam',
    'ten recent meetings cleared_at = 0' => 'Sepuluh pertemuan terakhir cleared_at = 0',
    'warn' => 'memperingatkan',
];