<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<Strong> Catatan: </ strong> Gunakan browser yang diperbarui untuk melihat komentar.',
    'Download' => 'Download',
    'Follow' => 'Mengikuti',
    'Fork' => 'Garpu',
    'Issue' => 'Isu',
    'Login with Facebook' => 'Masuk dengan Facebook',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Silahkan aktifkan JavaScript di browser anda untuk melihat Facebook {pluginName} Plugin dengan benar di situs ini',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Silahkan aktifkan JavaScript di browser anda untuk melihat Google {pluginName} Plugin dengan benar di situs ini',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'Silahkan aktifkan JavaScript di browser anda untuk melihat Twitter {pluginName} Plugin dengan benar di situs ini',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'Silahkan aktifkan JavaScript di browser anda untuk melihat VKontakte {pluginName} Plugin dengan benar di situs ini',
    'Please enable JavaScript to view the {pluginLink}.' => 'Silahkan aktifkan JavaScript untuk melihat {pluginLink} .',
    'Star' => 'Bintang',
    'Watch' => 'Menonton',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'Anda harus mengaktifkan Javascript di browser agar situs berfungsi optimal dan menampilkan bagian sepenuhnya.',
    'comments powered by Disqus' => 'Komentar didukung oleh Disqus',
];