<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# दोस्तों',
    '# Mtgs' => '# एमटीजीएस',
    '# Mtgs L30' => '# एमटीजीएस एल 30',
    '# Places' => '# स्थान',
    '# Prtcpnt' => '# प्रेट्सीपीएनटी',
    '# Prtcpnt L30' => '# प्रेट्स्प़न्ट एल 30',
    '#FB' => '# एफबी',
    '#Goog' => '#Goog',
    '#LkIn' => '# लुक इन',
    '#MComp' => '#MComp',
    '#MExp' => '# एमईएक्सपी',
    '#MPlan' => '# एमपीलेन',
    '#Plcs' => '#Plcs',
    '#Usrs' => '# यूज़र',
    '% Created Meeting' => '% बनाया बैठक',
    '% Created Meeting Last30' => '% बनाया बैठक Last30',
    '% Invited & Created Meeting' => '% आमंत्रित और बनाया बैठक',
    '%Prtcpnt' => '% Prtcpnt',
    '%Prtcpnt L30' => '% Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'इसका एक परीक्षण संस्करण प्रशासक को भेजा गया है।',
    'Action Text' => 'एक्शन टेक्स्ट',
    'Action Url' => 'क्रिया यूआरएल',
    'Are you sure you want to delete this item?' => 'क्या आप सुनिश्चित रूप से इस आइटम को मिटाना चाहते हैं?',
    'Caption' => 'कैप्शन',
    'Content' => 'सामग्री',
    'Create' => 'सर्जन करना',
    'Create Historical Data' => 'ऐतिहासिक डेटा बनाएं',
    'Create Launch' => 'लॉन्च बनाएं',
    'Create Message' => 'संदेश बनायें',
    'Create Message Log' => 'संदेश लॉग बनाएँ',
    'Create Place' => 'प्लेस बनाएं',
    'Create User' => 'उपयोगकर्ता बनाइये',
    'Create User Data' => 'उपयोगकर्ता डेटा बनाएँ',
    'Created At' => 'पर बनाया गया',
    'Date' => 'तारीख',
    'Delete' => 'हटाएं',
    'Domain' => 'डोमेन',
    'Ext' => 'एक्स्ट',
    'Frnds/Usr' => 'फ्रेंड्स / यूएसआर',
    'Historical Datas' => 'ऐतिहासिक डेटा',
    'Historical Statistics' => 'ऐतिहासिक सांख्यिकी',
    'ID' => 'आईडी',
    'Inv>Org' => 'INV> संगठन',
    'Is Social?' => 'सामाजिक है?',
    'Launches' => 'शुरूआत',
    'Level' => 'स्तर',
    'Meeting Planner' => 'बैठक नियोजक',
    'Message ID' => 'संदेश आईडी',
    'Message Logs' => 'संदेश लॉग्स',
    'Messages' => 'संदेश',
    'Mtgs/Usr' => 'Mtgs / Usr',
    'Places' => 'स्थान',
    'Plcs/Usr' => 'पीएलसीएस / यूएसआर',
    'Reset' => 'रीसेट',
    'Response' => 'प्रतिक्रिया',
    'Search' => 'खोज',
    'Sorry, we had a problem deleting your message.' => 'क्षमा करें, आपके संदेश को हटाने में हमें एक समस्या थी',
    'Status' => 'स्थिति',
    'Subject' => 'विषय',
    'Target' => 'लक्ष्य',
    'This message has been sent.' => 'यह संदेश भेजा गया है।',
    'UId' => 'UID',
    'Update' => 'अद्यतन',
    'Update {modelClass}: ' => 'अद्यतन {modelClass} :',
    'Updated At' => 'अपडेट किया गया',
    'User Data as of Yesterday' => 'उपयोगकर्ता के रूप में डेटा कल',
    'User Datas' => 'उपयोगकर्ता डाटा',
    'User ID' => 'यूज़र आईडी',
    'Users' => 'उपयोगकर्ता',
    'Your contacts have been imported.' => 'आपके संपर्क आयात किए गए हैं',
    'Your message has been deleted.' => 'आपका संदेश हटा दिया गया है।',
    'error!' => 'त्रुटि!',
    'ok' => 'ठीक',
    'one or more meetings not cleared_at in 24 hours' => '24 घंटों में एक या अधिक मीटिंग साफ़ नहीं हुई',
    'ten recent meetings cleared_at = 0' => 'दस हाल की मीटिंग्स cleared_at = 0',
    'warn' => 'चेतावनी',
];