<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Note:' => 'ध्यान दें:',
    'Your browser does not support {validation}. Try an alternative or more recent browser to access these features.' => 'आपका ब्राउज़र समर्थन नहीं करता है {validation} । इन सुविधाओं को एक्सेस करने के लिए वैकल्पिक या अधिक हाल के ब्राउज़र को आज़माएं',
    'file preview and multiple file upload' => 'फ़ाइल पूर्वावलोकन और एकाधिक फ़ाइल अपलोड',
    'multiple file upload' => 'एकाधिक फ़ाइल अपलोड',
];