<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<Strong> नोट: </ strong> टिप्पणियों को देखने के लिए कृपया एक अपडेट किए गए ब्राउज़र का उपयोग करें।',
    'Download' => 'डाउनलोड',
    'Follow' => 'का पालन करें',
    'Fork' => 'कांटा',
    'Issue' => 'मुद्दा',
    'Login with Facebook' => 'फेसबुक में जाये',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'कृपया फेसबुक को देखने के लिए अपने ब्राउज़र पर जावास्क्रिप्ट सक्षम करें {pluginName} इस साइट पर सही ढंग से प्लगइन',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'कृपया Google को देखने के लिए अपने ब्राउज़र पर JavaScript सक्षम करें {pluginName} इस साइट पर सही ढंग से प्लगइन',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'कृपया ट्विटर को देखने के लिए अपने ब्राउज़र पर JavaScript सक्षम करें {pluginName} इस साइट पर सही ढंग से प्लगइन',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'कृपया VKontakte को देखने के लिए अपने ब्राउज़र पर JavaScript सक्षम करें {pluginName} इस साइट पर सही ढंग से प्लगइन',
    'Please enable JavaScript to view the {pluginLink}.' => 'कृपया जावास्क्रिप्ट को देखने के लिए सक्षम करें {pluginLink} ।',
    'Star' => 'तारा',
    'Watch' => 'घड़ी',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'साइट को बेहतर ढंग से काम करने के लिए आपको अपने ब्राउज़र पर जावास्क्रिप्ट को सक्षम करना होगा और वर्गों को पूरी तरह से प्रदर्शित करना होगा।',
    'comments powered by Disqus' => 'टिप्पणियाँ Disqus द्वारा संचालित',
];