<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# Amici',
    '# Mtgs' => '# Mtgs',
    '# Mtgs L30' => '# Mtgs L30',
    '# Places' => '# Posti',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcpnt L30',
    '#FB' => '#fb',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '% Incontro creato',
    '% Created Meeting Last30' => '% Creato Incontro Last30',
    '% Invited & Created Meeting' => '% Invitato & Creato Meeting',
    '%Prtcpnt' => '% Prtcpnt',
    '%Prtcpnt L30' => '% Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'Una versione di prova è stata inviata agli amministratori.',
    'Action Text' => 'Testo dell\'azione',
    'Action Url' => 'Azione Url',
    'Are you sure you want to delete this item?' => 'Sei sicuro di voler eliminare questo articolo?',
    'Caption' => 'Didascalia',
    'Content' => 'Soddisfare',
    'Create' => 'Creare',
    'Create Historical Data' => 'Crea dati storici',
    'Create Launch' => 'Crea lancio',
    'Create Message' => 'Creare un messaggio',
    'Create Message Log' => 'Crea registro messaggi',
    'Create Place' => 'Crea posto',
    'Create User' => 'Creare un utente',
    'Create User Data' => 'Crea dati utente',
    'Created At' => 'Creato a',
    'Date' => 'Data',
    'Delete' => 'Elimina',
    'Domain' => 'Dominio',
    'Ext' => 'Ext',
    'Frnds/Usr' => 'Frnds / Usr',
    'Historical Datas' => 'Dati storici',
    'Historical Statistics' => 'Statistiche storiche',
    'ID' => 'ID',
    'Inv>Org' => 'Inv> Org',
    'Is Social?' => 'È sociale?',
    'Launches' => 'lancia',
    'Level' => 'Livello',
    'Meeting Planner' => 'Planner di riunione',
    'Message ID' => 'ID messaggio',
    'Message Logs' => 'Messaggi di messaggi',
    'Messages' => 'messaggi',
    'Mtgs/Usr' => 'Mtgs / Usr',
    'Places' => 'posti',
    'Plcs/Usr' => 'PLC / Usr',
    'Reset' => 'Reset',
    'Response' => 'Risposta',
    'Search' => 'Ricerca',
    'Sorry, we had a problem deleting your message.' => 'Spiacenti, abbiamo avuto un problema eliminando il tuo messaggio.',
    'Status' => 'Stato',
    'Subject' => 'Soggetto',
    'Target' => 'Bersaglio',
    'This message has been sent.' => 'Questo messaggio è stato inviato.',
    'UId' => 'UId',
    'Update' => 'Aggiornare',
    'Update {modelClass}: ' => 'Aggiornare {modelClass} :',
    'Updated At' => 'Aggiornato a',
    'User Data as of Yesterday' => 'Dati utente da ieri',
    'User Datas' => 'Dati utente',
    'User ID' => 'ID utente',
    'Users' => 'utenti',
    'Your contacts have been imported.' => 'I tuoi contatti sono stati importati.',
    'Your message has been deleted.' => 'Il tuo messaggio è stato eliminato.',
    'error!' => 'errore!',
    'ok' => 'ok',
    'one or more meetings not cleared_at in 24 hours' => 'Una o più riunioni non cancellate in 24 ore',
    'ten recent meetings cleared_at = 0' => 'Dieci riunioni recenti cleared_at = 0',
    'warn' => 'avvisare',
];