<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<Strong> Nota: </ strong> Utilizza un browser aggiornato per visualizzare i commenti.',
    'Download' => 'Scaricare',
    'Follow' => 'Segui',
    'Fork' => 'Forchetta',
    'Issue' => 'Problema',
    'Login with Facebook' => 'Fai il login con facebook',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Attiva JavaScript sul tuo browser per visualizzare Facebook {pluginName} Plug in correttamente su questo sito.',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Attiva JavaScript sul tuo browser per visualizzare Google {pluginName} Plug in correttamente su questo sito.',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'Attiva JavaScript sul tuo browser per visualizzare Twitter {pluginName} Plug in correttamente su questo sito.',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'Abilita JavaScript sul tuo browser per visualizzare il VKontakte {pluginName} Plug in correttamente su questo sito.',
    'Please enable JavaScript to view the {pluginLink}.' => 'Si prega di abilitare JavaScript per visualizzare il {pluginLink} .',
    'Star' => 'Stella',
    'Watch' => 'Orologio',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'È necessario attivare Javascript nel browser per il sito per funzionare in modo ottimale e visualizzare le sezioni completamente.',
    'comments powered by Disqus' => 'Commenti forniti da Disqus',
];