<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Are you sure you want to delete this item?' => 'Czy na pewno chcesz usunąć ten element?',
    'Create' => 'Stwórz',
    'Create User' => 'Stwórz użytkownika',
    'Created At' => 'Utworzone w',
    'Delete' => 'Kasować',
    'ID' => 'ID',
    'Reset' => 'Nastawić',
    'Search' => 'Szukanie',
    'Token' => 'Znak',
    'Update' => 'Aktualizacja',
    'Update {modelClass}: ' => 'Aktualizacja {modelClass} :',
    'Updated At' => 'Zaktualizowano na',
    'User ID' => 'identyfikator użytkownika',
    'Users' => 'Użytkownicy',
];