<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# Przyjaciele',
    '# Mtgs' => '# Mtgs',
    '# Mtgs L30' => '# Mt30',
    '# Places' => '# Miejsca',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcpnt L30',
    '#FB' => '#PEŁNE WYŻYWIENIE',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#Mkompres',
    '#MExp' => '#Exp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '# Szt',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '% Stworzenie spotkania',
    '% Created Meeting Last30' => '% Utworzono spotkanie Last30',
    '% Invited & Created Meeting' => '% Zaproszenie i spotkanie',
    '%Prtcpnt' => '% Prtcpnt',
    '%Prtcpnt L30' => '% Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'Wersja testowa została wysłana administratorom.',
    'Action Text' => 'Tekst działań',
    'Action Url' => 'Adres URL działania',
    'Are you sure you want to delete this item?' => 'Czy na pewno chcesz usunąć ten element?',
    'Caption' => 'Podpis',
    'Content' => 'Zadowolony',
    'Create' => 'Stwórz',
    'Create Historical Data' => 'Utwórz dane historyczne',
    'Create Launch' => 'Utwórz Uruchom',
    'Create Message' => 'Stwórz wiadomość',
    'Create Message Log' => 'Utwórz dziennik wiadomości',
    'Create Place' => 'Utwórz miejsce',
    'Create User' => 'Stwórz użytkownika',
    'Create User Data' => 'Utwórz dane użytkownika',
    'Created At' => 'Utworzone w',
    'Date' => 'Data',
    'Delete' => 'Kasować',
    'Domain' => 'Domena',
    'Ext' => 'Ext',
    'Frnds/Usr' => 'Frnds / Usr',
    'Historical Datas' => 'Dane historyczne',
    'Historical Statistics' => 'Statystyki historyczne',
    'ID' => 'ID',
    'Inv>Org' => 'Inv> Org',
    'Is Social?' => 'Czy społeczne?',
    'Launches' => 'Uruchamia',
    'Level' => 'Poziom',
    'Meeting Planner' => 'Planer spotkania',
    'Message ID' => 'Identyfikator wiadomości',
    'Message Logs' => 'Dzienniki wiadomości',
    'Messages' => 'Wiadomości',
    'Mtgs/Usr' => 'Mtgs / Usr',
    'Places' => 'Miejsca',
    'Plcs/Usr' => 'Plcs / Usr',
    'Reset' => 'Nastawić',
    'Response' => 'Odpowiedź',
    'Search' => 'Szukanie',
    'Sorry, we had a problem deleting your message.' => 'Niestety, mieliśmy problem z usunięciem wiadomości.',
    'Status' => 'Status',
    'Subject' => 'Przedmiot',
    'Target' => 'Cel',
    'This message has been sent.' => 'Ta wiadomość została wysłana.',
    'UId' => 'UId',
    'Update' => 'Aktualizacja',
    'Update {modelClass}: ' => 'Aktualizacja {modelClass} :',
    'Updated At' => 'Zaktualizowano na',
    'User Data as of Yesterday' => 'Dane użytkownika od wczoraj',
    'User Datas' => 'Dane użytkownika',
    'User ID' => 'identyfikator użytkownika',
    'Users' => 'Użytkownicy',
    'Your contacts have been imported.' => 'Twoje kontakty zostały zaimportowane.',
    'Your message has been deleted.' => 'Twoja wiadomość została usunięta.',
    'error!' => 'błąd!',
    'ok' => 'ok',
    'one or more meetings not cleared_at in 24 hours' => 'Jeden lub więcej spotkań, które nie zostały zatwierdzone w ciągu 24 godzin',
    'ten recent meetings cleared_at = 0' => 'Dziesięć ostatnich spotkań clear_at = 0',
    'warn' => 'ostrzec',
];