<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<Strong> Uwaga: </ strong> Proszę użyć zaktualizowanej przeglądarki, aby wyświetlić komentarze.',
    'Download' => 'Pobieranie',
    'Follow' => 'Śledzić',
    'Fork' => 'Widelec',
    'Issue' => 'Kwestia',
    'Login with Facebook' => 'Zaloguj się przez facebook',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Włącz obsługę języka JavaScript w przeglądarce {pluginName} Plugin poprawnie w tej witrynie.',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Włącz obsługę języka JavaScript w przeglądarce {pluginName} Plugin poprawnie w tej witrynie.',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'Włącz obsługę języka JavaScript w przeglądarce {pluginName} Plugin poprawnie w tej witrynie.',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'Włącz obsługę języka JavaScript w przeglądarce, aby wyświetlić VKontakte {pluginName} Plugin poprawnie w tej witrynie.',
    'Please enable JavaScript to view the {pluginLink}.' => 'Włącz obsługę JavaScript w celu wyświetlenia {pluginLink} .',
    'Star' => 'Gwiazda',
    'Watch' => 'Zegarek',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'Musisz włączyć obsługę Javascript w swojej przeglądarce, aby strona mogła optymalnie i wyświetlać sekcje.',
    'comments powered by Disqus' => 'Komentarze powered by Disqus',
];