<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Are you sure you want to delete this item?' => 'Sind Sie sicher, dass Sie diesen Artikel löschen möchten?',
    'Create' => 'Erstellen',
    'Create User' => 'Benutzer erstellen',
    'Created At' => 'Hergestellt in',
    'Delete' => 'Löschen',
    'ID' => 'ICH WÜRDE',
    'Reset' => 'Zurücksetzen',
    'Search' => 'Suche',
    'Token' => 'Token',
    'Update' => 'Aktualisieren',
    'Update {modelClass}: ' => 'Aktualisieren {modelClass} Aufrechtzuerhalten.',
    'Updated At' => 'Aktualisiert bei',
    'User ID' => 'Benutzeridentifikation',
    'Users' => 'Benutzer',
];