<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# Freunde',
    '# Mtgs' => '# Mtgs',
    '# Mtgs L30' => '# Mtgs L30',
    '# Places' => '# Setzt',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcpnt L30',
    '#FB' => '#FB',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '% Erstellt Treffen',
    '% Created Meeting Last30' => '% Erstellt Meeting Last30',
    '% Invited & Created Meeting' => '% Eingeladen und geschafft Meeting',
    '%Prtcpnt' => '% Prtcpnt',
    '%Prtcpnt L30' => '% Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'Eine Testversion wurde an Administratoren gesendet.',
    'Action Text' => 'Aktionstext',
    'Action Url' => 'Aktion Url',
    'Are you sure you want to delete this item?' => 'Sind Sie sicher, dass Sie diesen Artikel löschen möchten?',
    'Caption' => 'Bildunterschrift',
    'Content' => 'Inhalt',
    'Create' => 'Erstellen',
    'Create Historical Data' => 'Erstellen Sie historische Daten',
    'Create Launch' => 'Starten starten',
    'Create Message' => 'Nachricht erstellen',
    'Create Message Log' => 'Meldungsprotokoll erstellen',
    'Create Place' => 'Platz anlegen',
    'Create User' => 'Benutzer erstellen',
    'Create User Data' => 'Benutzerdaten erstellen',
    'Created At' => 'Hergestellt in',
    'Date' => 'Datum',
    'Delete' => 'Löschen',
    'Domain' => 'Domain',
    'Ext' => 'Ext',
    'Frnds/Usr' => 'Frnds / Usr',
    'Historical Datas' => 'Historische Daten',
    'Historical Statistics' => 'Historische Statistik',
    'ID' => 'ICH WÜRDE',
    'Inv>Org' => 'Inv> Org',
    'Is Social?' => 'Ist sozial?',
    'Launches' => 'Startet',
    'Level' => 'Ebene',
    'Meeting Planner' => 'Besprechungsplaner',
    'Message ID' => 'Nachrichten ID',
    'Message Logs' => 'Meldungsprotokolle',
    'Messages' => 'Meldungen',
    'Mtgs/Usr' => 'Mtgs / Usr',
    'Places' => 'Setzt',
    'Plcs/Usr' => 'Plcs / usr',
    'Reset' => 'Zurücksetzen',
    'Response' => 'Antwort',
    'Search' => 'Suche',
    'Sorry, we had a problem deleting your message.' => 'Sorry, wir hatten ein Problem beim Löschen Ihrer Nachricht.',
    'Status' => 'Status',
    'Subject' => 'Fach',
    'Target' => 'Ziel',
    'This message has been sent.' => 'Diese Nachricht wurde gesendet.',
    'UId' => 'UId',
    'Update' => 'Aktualisieren',
    'Update {modelClass}: ' => 'Aktualisieren {modelClass} Aufrechtzuerhalten.',
    'Updated At' => 'Aktualisiert bei',
    'User Data as of Yesterday' => 'Benutzerdaten ab gestern',
    'User Datas' => 'Benutzerdaten',
    'User ID' => 'Benutzeridentifikation',
    'Users' => 'Benutzer',
    'Your contacts have been imported.' => 'Ihre Kontakte wurden importiert.',
    'Your message has been deleted.' => 'Ihre Nachricht wurde gelöscht.',
    'error!' => 'Fehler!',
    'ok' => 'OK',
    'one or more meetings not cleared_at in 24 hours' => 'Ein oder mehrere Treffen nicht in 24 Stunden gelöscht',
    'ten recent meetings cleared_at = 0' => 'Zehn jüngste Treffen cleared_at = 0',
    'warn' => 'warnen',
];