<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# Přátelé',
    '# Mtgs' => '# Mtgs',
    '# Mtgs L30' => '# Mtgs L30',
    '# Places' => '# Places',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcpnt L30',
    '#FB' => '#FB',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '% Vytvořeno schůzka',
    '% Created Meeting Last30' => '% Vytvořeno schůzka Last30',
    '% Invited & Created Meeting' => '% Pozvánky a setkání',
    '%Prtcpnt' => '% Prtcpnt',
    '%Prtcpnt L30' => '% Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'Testovací verze této zprávy byla odeslána správcům.',
    'Action Text' => 'Text akce',
    'Action Url' => 'Url akce',
    'Are you sure you want to delete this item?' => 'Opravdu chcete tuto položku smazat?',
    'Caption' => 'Titulek',
    'Content' => 'Obsah',
    'Create' => 'Vytvořit',
    'Create Historical Data' => 'Vytvořte historická data',
    'Create Launch' => 'Vytvořit spuštění',
    'Create Message' => 'Vytvořit zprávu',
    'Create Message Log' => 'Vytvořit protokol zpráv',
    'Create Place' => 'Vytvořit místo',
    'Create User' => 'Vytvořit uživatele',
    'Create User Data' => 'Vytvořte uživatelská data',
    'Created At' => 'Vytvořeno na',
    'Date' => 'datum',
    'Delete' => 'Vymazat',
    'Domain' => 'Doména',
    'Ext' => 'Ext',
    'Frnds/Usr' => 'Frnds / Usr',
    'Historical Datas' => 'Historické údaje',
    'Historical Statistics' => 'Historická statistika',
    'ID' => 'ID',
    'Inv>Org' => 'Inv> Org',
    'Is Social?' => 'Je sociální?',
    'Launches' => 'Spustí',
    'Level' => 'Úroveň',
    'Meeting Planner' => 'Plánovač schůzek',
    'Message ID' => 'ID zprávy',
    'Message Logs' => 'Zprávy zpráv',
    'Messages' => 'Zprávy',
    'Mtgs/Usr' => 'Mtgs / Usr',
    'Places' => 'Místa',
    'Plcs/Usr' => 'Plcs / Usr',
    'Reset' => 'Resetovat',
    'Response' => 'Odezva',
    'Search' => 'Vyhledávání',
    'Sorry, we had a problem deleting your message.' => 'Je nám líto, došlo k potížím s odstraněním zprávy.',
    'Status' => 'Postavení',
    'Subject' => 'Předmět',
    'Target' => 'cílová',
    'This message has been sent.' => 'Tato zpráva byla odeslána.',
    'UId' => 'UId',
    'Update' => 'Aktualizace',
    'Update {modelClass}: ' => 'Aktualizace {modelClass} :',
    'Updated At' => 'Aktualizováno na',
    'User Data as of Yesterday' => 'Uživatelské údaje k dnešnímu dni',
    'User Datas' => 'Uživatelské údaje',
    'User ID' => 'uživatelské ID',
    'Users' => 'Uživatelé',
    'Your contacts have been imported.' => 'Vaše kontakty byly importovány.',
    'Your message has been deleted.' => 'Vaše zpráva byla smazána.',
    'error!' => 'chyba!',
    'ok' => 'OK',
    'one or more meetings not cleared_at in 24 hours' => 'Jedna nebo více schůzek nebylo zrušeno za 24 hodin',
    'ten recent meetings cleared_at = 0' => 'Deset nedávných schůzek cleared_at = 0',
    'warn' => 'varovat',
];