<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# Friends',
    '# Mtgs' => '# Mtgs',
    '# Mtgs L30' => '# Mtgs L30',
    '# Places' => '# Places',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcpnt L30',
    '#FB' => '#FB',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '% Created Meeting',
    '% Created Meeting Last30' => '% Created Meeting Last30',
    '% Invited & Created Meeting' => '% Invited & Created Meeting',
    '%Prtcpnt' => '%Prtcpnt',
    '%Prtcpnt L30' => '%Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'A test version of this has been sent to administrators.',
    'Action Text' => 'Action Text',
    'Action Url' => 'Action Url',
    'Are you sure you want to delete this item?' => 'Are you sure you want to delete this item?',
    'Caption' => 'Caption',
    'Content' => 'Content',
    'Create' => 'Create',
    'Create Historical Data' => 'Create Historical Data',
    'Create Launch' => 'Create Launch',
    'Create Message' => 'Create Message',
    'Create Message Log' => 'Create Message Log',
    'Create Place' => 'Create Place',
    'Create User' => 'Create User',
    'Create User Data' => 'Create User Data',
    'Created At' => 'Created At',
    'Date' => 'Date',
    'Delete' => 'Delete',
    'Domain' => 'Domain',
    'Ext' => 'Ext',
    'Frnds/Usr' => 'Frnds/Usr',
    'Historical Datas' => 'Historical Datas',
    'Historical Statistics' => 'Historical Statistics',
    'ID' => 'ID',
    'Inv>Org' => 'Inv>Org',
    'Is Social?' => 'Is Social?',
    'Launches' => 'Launches',
    'Level' => 'Level',
    'Meeting Planner' => 'Meeting Planner',
    'Message ID' => 'Message ID',
    'Message Logs' => 'Message Logs',
    'Messages' => 'Messages',
    'Mtgs/Usr' => 'Mtgs/Usr',
    'Places' => 'Places',
    'Plcs/Usr' => 'Plcs/Usr',
    'Reset' => 'Reset',
    'Response' => 'Response',
    'Search' => 'Search',
    'Sorry, we had a problem deleting your message.' => 'Sorry, we had a problem deleting your message.',
    'Status' => 'Status',
    'Subject' => 'Subject',
    'Target' => 'Target',
    'This message has been sent.' => 'This message has been sent.',
    'UId' => 'UId',
    'Update' => 'Update',
    'Update {modelClass}: ' => 'Update {modelClass} :',
    'Updated At' => 'Updated At',
    'User Data as of Yesterday' => 'User Data as of Yesterday',
    'User Datas' => 'User Datas',
    'User ID' => 'User ID',
    'Users' => 'Users',
    'Your contacts have been imported.' => 'Your contacts have been imported.',
    'Your message has been deleted.' => 'Your message has been deleted.',
    'error!' => 'error!',
    'ok' => 'ok',
    'one or more meetings not cleared_at in 24 hours' => 'one or more meetings not cleared_at in 24 hours',
    'ten recent meetings cleared_at = 0' => 'ten recent meetings cleared_at = 0',
    'warn' => 'warn',
];