<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# Οι φιλοι',
    '# Mtgs' => '# Mtgs',
    '# Mtgs L30' => '# Mtgs L30',
    '# Places' => '# Places',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcpnt L30',
    '#FB' => '# FB',
    '#Goog' => '#Gog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => 'Δημιουργήθηκε συνάντηση%',
    '% Created Meeting Last30' => '% Δημιουργία συνάντησης Last30',
    '% Invited & Created Meeting' => '% Πρόσκληση & δημιουργία συνάντησης',
    '%Prtcpnt' => '% Prtcpnt',
    '%Prtcpnt L30' => '% Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'Μια δοκιμαστική έκδοση αυτού έχει σταλεί στους διαχειριστές.',
    'Action Text' => 'Κείμενο δράσης',
    'Action Url' => 'Url δράσης',
    'Are you sure you want to delete this item?' => 'Είστε σίγουροι ότι θέλετε να διαγράψετε αυτό το στοιχείο;',
    'Caption' => 'Λεζάντα',
    'Content' => 'Περιεχόμενο',
    'Create' => 'Δημιουργώ',
    'Create Historical Data' => 'Δημιουργία ιστορικών δεδομένων',
    'Create Launch' => 'Δημιουργία εκκίνησης',
    'Create Message' => 'Δημιουργία μηνύματος',
    'Create Message Log' => 'Δημιουργία αρχείου μηνυμάτων',
    'Create Place' => 'Δημιουργία θέσης',
    'Create User' => 'Δημιουργία χρήστη',
    'Create User Data' => 'Δημιουργία δεδομένων χρήστη',
    'Created At' => 'Δημιουργήθηκε στο',
    'Date' => 'Ημερομηνία',
    'Delete' => 'Διαγράφω',
    'Domain' => 'Τομέα',
    'Ext' => 'Ext',
    'Frnds/Usr' => 'Frnds / Usr',
    'Historical Datas' => 'Ιστορικά δεδομένα',
    'Historical Statistics' => 'Ιστορικές Στατιστικές',
    'ID' => 'ταυτότητα',
    'Inv>Org' => 'Inv> Org',
    'Is Social?' => 'Είναι κοινωνική;',
    'Launches' => 'Εκτοξεύει',
    'Level' => 'Επίπεδο',
    'Meeting Planner' => 'Συντονιστής συναντήσεων',
    'Message ID' => 'Αναγνωριστικό μηνύματος',
    'Message Logs' => 'Μητρώα μηνυμάτων',
    'Messages' => 'Μηνύματα',
    'Mtgs/Usr' => 'Mtgs / Usr',
    'Places' => 'Μέρη',
    'Plcs/Usr' => 'Plcs / Usr',
    'Reset' => 'Επαναφορά',
    'Response' => 'Απάντηση',
    'Search' => 'Ψάξιμο',
    'Sorry, we had a problem deleting your message.' => 'Λυπούμαστε, είχαμε ένα πρόβλημα κατά τη διαγραφή του μηνύματός σας.',
    'Status' => 'Κατάσταση',
    'Subject' => 'Θέμα',
    'Target' => 'Στόχος',
    'This message has been sent.' => 'Αυτό το μήνυμα έχει σταλεί.',
    'UId' => 'UId',
    'Update' => 'Εκσυγχρονίζω',
    'Update {modelClass}: ' => 'Εκσυγχρονίζω {modelClass} :',
    'Updated At' => 'Ενημερώθηκε στο',
    'User Data as of Yesterday' => 'Δεδομένα χρηστών από χθες',
    'User Datas' => 'Δεδομένα χρήστη',
    'User ID' => 'ταυτότητα χρήστη',
    'Users' => 'Χρήστες',
    'Your contacts have been imported.' => 'Οι επαφές σας έχουν εισαχθεί.',
    'Your message has been deleted.' => 'Το μήνυμά σας έχει διαγραφεί.',
    'error!' => 'λάθος!',
    'ok' => 'Εντάξει',
    'one or more meetings not cleared_at in 24 hours' => 'Μία ή περισσότερες συνεδριάσεις δεν έχουν εκκαθαριστεί σε 24 ώρες',
    'ten recent meetings cleared_at = 0' => 'Δέκα πρόσφατες συναντήσεις cleared_at = 0',
    'warn' => 'προειδοποιώ',
];