<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<Strong> Σημείωση: </ strong> Χρησιμοποιήστε ένα ενημερωμένο πρόγραμμα περιήγησης για να δείτε σχόλια.',
    'Download' => 'Κατεβάστε',
    'Follow' => 'Ακολουθηστε',
    'Fork' => 'Πιρούνι',
    'Issue' => 'Θέμα',
    'Login with Facebook' => 'Σύνδεση με το Facebook',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Παρακαλούμε ενεργοποιήστε το JavaScript στον browser σας για να δείτε το Facebook {pluginName} Plugin σωστά σε αυτόν τον ιστότοπο.',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Παρακαλούμε ενεργοποιήστε το JavaScript στον browser σας για να δείτε το Google {pluginName} Plugin σωστά σε αυτόν τον ιστότοπο.',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'Παρακαλούμε ενεργοποιήστε το JavaScript στον browser σας για να δείτε το Twitter {pluginName} Plugin σωστά σε αυτόν τον ιστότοπο.',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'Παρακαλούμε ενεργοποιήστε το JavaScript στον browser σας για να δείτε το VKontakte {pluginName} Plugin σωστά σε αυτόν τον ιστότοπο.',
    'Please enable JavaScript to view the {pluginLink}.' => 'Παρακαλούμε ενεργοποιήστε το JavaScript για να δείτε το {pluginLink} .',
    'Star' => 'Αστέρι',
    'Watch' => 'Παρακολουθώ',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'Πρέπει να ενεργοποιήσετε το Javascript στον περιηγητή σας, ώστε ο ιστότοπος να λειτουργεί άριστα και να εμφανίζει εντελώς ενότητες.',
    'comments powered by Disqus' => 'Σχόλια powered by Disqus',
];