<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Are you sure you want to delete this item?' => '이 항목을 삭제 하시겠습니까?',
    'Create' => '몹시 떠들어 대다',
    'Create User' => '사용자 생성',
    'Created At' => '작성 시간',
    'Delete' => '지우다',
    'ID' => '신분증',
    'Reset' => '다시 놓기',
    'Search' => '수색',
    'Token' => '토큰',
    'Update' => '최신 정보',
    'Update {modelClass}: ' => '최신 정보 {modelClass} :',
    'Updated At' => '에서 업데이트 됨',
    'User ID' => '사용자 ID',
    'Users' => '사용자',
];