<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# 친구',
    '# Mtgs' => '# Mtgs',
    '# Mtgs L30' => '# Mtgs L30',
    '# Places' => '# 장소',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcpnt L30',
    '#FB' => '#FB',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '만든 회의 % 생성',
    '% Created Meeting Last30' => '회의 생성 완료 % 30',
    '% Invited & Created Meeting' => '초대 된 초대 회의 및 초대 된 회의 (%)',
    '%Prtcpnt' => '% Prtcpnt',
    '%Prtcpnt L30' => '% Prtcpnt L30',
    'A test version of this has been sent to administrators.' => '이 테스트 버전이 관리자에게 전송되었습니다.',
    'Action Text' => '액션 텍스트',
    'Action Url' => '작업 URL',
    'Are you sure you want to delete this item?' => '이 항목을 삭제 하시겠습니까?',
    'Caption' => '표제',
    'Content' => '함유량',
    'Create' => '몹시 떠들어 대다',
    'Create Historical Data' => '과거 데이터 생성',
    'Create Launch' => '시작 만들기',
    'Create Message' => '메시지 작성',
    'Create Message Log' => '메시지 로그 작성',
    'Create Place' => '장소 만들기',
    'Create User' => '사용자 생성',
    'Create User Data' => '사용자 데이터 생성',
    'Created At' => '작성 시간',
    'Date' => '날짜',
    'Delete' => '지우다',
    'Domain' => '도메인',
    'Ext' => 'Ext',
    'Frnds/Usr' => 'Frnds / Usr',
    'Historical Datas' => '역사적인 데이터',
    'Historical Statistics' => '역사 통계',
    'ID' => '신분증',
    'Inv>Org' => 'Inv> 조직',
    'Is Social?' => '소셜인가?',
    'Launches' => '출시',
    'Level' => '수평',
    'Meeting Planner' => '회의 플래너',
    'Message ID' => '메시지 ID',
    'Message Logs' => '메시지 로그',
    'Messages' => '메시지',
    'Mtgs/Usr' => 'Mtgs / Usr',
    'Places' => '장소',
    'Plcs/Usr' => 'Plcs / Usr',
    'Reset' => '다시 놓기',
    'Response' => '응답',
    'Search' => '수색',
    'Sorry, we had a problem deleting your message.' => '죄송합니다. 메시지를 삭제하는 중에 문제가 발생했습니다.',
    'Status' => '지위',
    'Subject' => '제목',
    'Target' => '목표',
    'This message has been sent.' => '이 메시지가 전송되었습니다.',
    'UId' => 'UId',
    'Update' => '최신 정보',
    'Update {modelClass}: ' => '최신 정보 {modelClass} :',
    'Updated At' => '에서 업데이트 됨',
    'User Data as of Yesterday' => '어제 현재 사용자 데이터',
    'User Datas' => '사용자 데이터',
    'User ID' => '사용자 ID',
    'Users' => '사용자',
    'Your contacts have been imported.' => '주소록을 가져 왔습니다.',
    'Your message has been deleted.' => '메시지가 삭제되었습니다.',
    'error!' => '오류!',
    'ok' => '승인',
    'one or more meetings not cleared_at in 24 hours' => '24 시간 내에 하나 이상의 회의가 cleared_at에 있지 않음',
    'ten recent meetings cleared_at = 0' => '최근 모임 10 회 cleared_at = 0',
    'warn' => '경고하다',
];