<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<strong> 참고 사항 : </ strong> 의견을 보려면 업데이트 된 브라우저를 사용하십시오.',
    'Download' => '다운로드',
    'Follow' => '따르다',
    'Fork' => '포크',
    'Issue' => '발행물',
    'Login with Facebook' => '페이스 북으로 로그인',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Facebook에서 Facebook을 보려면 브라우저에서 JavaScript를 활성화하십시오. {pluginName} 플러그인을이 사이트에 올립니다.',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Google을 보려면 브라우저에서 JavaScript를 활성화하십시오. {pluginName} 플러그인을이 사이트에 올립니다.',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => '트위터를 보려면 브라우저에서 JavaScript를 활성화하십시오. {pluginName} 플러그인을이 사이트에 올립니다.',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'VKontakte를 보려면 브라우저에서 JavaScript를 활성화하십시오. {pluginName} 플러그인을이 사이트에 올립니다.',
    'Please enable JavaScript to view the {pluginLink}.' => '웹 사이트를 보려면 JavaScript를 활성화하십시오. {pluginLink} .',
    'Star' => '별',
    'Watch' => '손목 시계',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => '사이트가 최적으로 작동하고 섹션을 완전히 표시하려면 브라우저에서 Javascript를 활성화해야합니다.',
    'comments powered by Disqus' => 'Disqus가 제공 한 의견',
];