<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# Bạn bè',
    '# Mtgs' => '# Mtgs',
    '# Mtgs L30' => '# Mtgs L30',
    '# Places' => '# Nơi',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcpnt L30',
    '#FB' => '#FB',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '% Đã tạo cuộc họp',
    '% Created Meeting Last30' => '% Đã tổ chức cuộc họp Cuối cùng30',
    '% Invited & Created Meeting' => '% Đã mời và tạo Cuộc họp',
    '%Prtcpnt' => '% Prtcpnt',
    '%Prtcpnt L30' => '% Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'Phiên bản thử nghiệm này đã được gửi tới các quản trị viên.',
    'Action Text' => 'Văn bản hành động',
    'Action Url' => 'Url Hành động',
    'Are you sure you want to delete this item?' => 'bạn có chắc bạn muốn xóa mục này?',
    'Caption' => 'Chú thích',
    'Content' => 'Nội dung',
    'Create' => 'Tạo nên',
    'Create Historical Data' => 'Tạo dữ liệu lịch sử',
    'Create Launch' => 'Tạo Khởi chạy',
    'Create Message' => 'Soạn tin nhắn',
    'Create Message Log' => 'Tạo nhật ký thư',
    'Create Place' => 'Tạo địa điểm',
    'Create User' => 'Tạo người dùng',
    'Create User Data' => 'Tạo dữ liệu người dùng',
    'Created At' => 'Tạo ra',
    'Date' => 'Ngày',
    'Delete' => 'Xóa bỏ',
    'Domain' => 'Miền',
    'Ext' => 'Mở rộng',
    'Frnds/Usr' => 'Frnds / Usr',
    'Historical Datas' => 'Dữ liệu lịch sử',
    'Historical Statistics' => 'Thống kê lịch sử',
    'ID' => 'ID',
    'Inv>Org' => 'Inv> Tổ chức',
    'Is Social?' => 'Xã hội là gì?',
    'Launches' => 'Ra mắt',
    'Level' => 'Cấp độ',
    'Meeting Planner' => 'Người tổ chức cuộc họp',
    'Message ID' => 'ID tin nhắn',
    'Message Logs' => 'Nhật ký thông báo',
    'Messages' => 'Tin nhắn',
    'Mtgs/Usr' => 'Mtgs / Usr',
    'Places' => 'Nơi',
    'Plcs/Usr' => 'Plcs / Usr',
    'Reset' => 'Đặt lại',
    'Response' => 'Phản ứng',
    'Search' => 'Tìm kiếm',
    'Sorry, we had a problem deleting your message.' => 'Rất tiếc, chúng tôi đã gặp sự cố khi xóa tin nhắn của bạn.',
    'Status' => 'Trạng thái',
    'Subject' => 'Môn học',
    'Target' => 'Mục tiêu',
    'This message has been sent.' => 'Thư này đã được gửi.',
    'UId' => 'UId',
    'Update' => 'Cập nhật',
    'Update {modelClass}: ' => 'Cập nhật {modelClass} :',
    'Updated At' => 'Cập nhật tại',
    'User Data as of Yesterday' => 'Dữ liệu Người dùng kể từ ngày hôm qua',
    'User Datas' => 'User Datas',
    'User ID' => 'Tên người dùng',
    'Users' => 'Người sử dụng',
    'Your contacts have been imported.' => 'Địa chỉ liên hệ của bạn đã được nhập.',
    'Your message has been deleted.' => 'Tin nhắn của bạn đã bị xóa.',
    'error!' => 'lỗi!',
    'ok' => 'được',
    'one or more meetings not cleared_at in 24 hours' => 'Một hoặc nhiều cuộc họp không được thông báo trong 24 giờ',
    'ten recent meetings cleared_at = 0' => 'Mười cuộc họp gần đây đã được thông báo clear_at = 0',
    'warn' => 'cảnh báo',
];