<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Note:' => 'Chú thích:',
    'Your browser does not support {validation}. Try an alternative or more recent browser to access these features.' => 'Trình duyệt của bạn không hỗ trợ {validation} . Hãy thử một trình duyệt khác hoặc mới hơn để truy cập các tính năng này.',
    'file preview and multiple file upload' => 'Xem trước tập tin và tải lên nhiều file',
    'multiple file upload' => 'Tải lên nhiều tệp tin',
];