<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<Strong> Lưu ý: </ strong> Vui lòng sử dụng trình duyệt đã cập nhật để xem nhận xét.',
    'Download' => 'Tải về',
    'Follow' => 'Theo',
    'Fork' => 'Cái nĩa',
    'Issue' => 'Vấn đề',
    'Login with Facebook' => 'Đăng nhập Facebook',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Vui lòng bật JavaScript trên trình duyệt của bạn để xem Facebook {pluginName} Plugin chính xác trên trang web này.',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Vui lòng bật JavaScript trên trình duyệt của bạn để xem Google {pluginName} Plugin chính xác trên trang web này.',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'Vui lòng bật JavaScript trên trình duyệt của bạn để xem Twitter {pluginName} Plugin chính xác trên trang web này.',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'Vui lòng bật JavaScript trên trình duyệt của bạn để xem VKontakte {pluginName} Plugin chính xác trên trang web này.',
    'Please enable JavaScript to view the {pluginLink}.' => 'Vui lòng bật JavaScript để xem {pluginLink} .',
    'Star' => 'Ngôi sao',
    'Watch' => 'Đồng hồ đeo tay',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'Bạn phải bật Javascript trên trình duyệt của bạn để trang web hoạt động tối ưu và hiển thị các phần hoàn toàn.',
    'comments powered by Disqus' => 'Nhận xét được cung cấp bởi Disqus',
];