<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Are you sure you want to delete this item?' => 'هل أنت متأكد أنك تريد حذف هذا البند؟',
    'Create' => 'خلق',
    'Create User' => 'إنشاء مستخدم',
    'Created At' => 'أنشئت في',
    'Delete' => 'حذف',
    'ID' => 'هوية شخصية',
    'Reset' => 'إعادة تعيين',
    'Search' => 'بحث',
    'Token' => 'الرمز المميز',
    'Update' => 'تحديث',
    'Update {modelClass}: ' => 'تحديث {modelClass} :',
    'Updated At' => 'تم التحديث في',
    'User ID' => 'معرف المستخدم',
    'Users' => 'المستخدمون',
];