<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# اصحاب',
    '# Mtgs' => '# متس',
    '# Mtgs L30' => '# متس L30',
    '# Places' => '# أماكن',
    '# Prtcpnt' => '# برتكبنت',
    '# Prtcpnt L30' => '# برتكبنت L30',
    '#FB' => '#FB',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '٪ كريتد ميتينغ',
    '% Created Meeting Last30' => '٪ كريتد ميتينغ Last30',
    '% Invited & Created Meeting' => '٪ الاجتماع المدعو والمكون',
    '%Prtcpnt' => '٪ برتكبنت',
    '%Prtcpnt L30' => '٪ برتكبنت L30',
    'A test version of this has been sent to administrators.' => 'تم إرسال نسخة تجريبية من هذا إلى المشرفين.',
    'Action Text' => 'نص الإجراء',
    'Action Url' => 'عنوان ورل للعمل',
    'Are you sure you want to delete this item?' => 'هل أنت متأكد أنك تريد حذف هذا البند؟',
    'Caption' => 'شرح',
    'Content' => 'يحتوى',
    'Create' => 'خلق',
    'Create Historical Data' => 'إنشاء بيانات تاريخية',
    'Create Launch' => 'إنشاء إطلاق',
    'Create Message' => 'إنشاء رسالة',
    'Create Message Log' => 'إنشاء سجل رسالة',
    'Create Place' => 'إنشاء مكان',
    'Create User' => 'إنشاء مستخدم',
    'Create User Data' => 'إنشاء بيانات المستخدم',
    'Created At' => 'أنشئت في',
    'Date' => 'تاريخ',
    'Delete' => 'حذف',
    'Domain' => 'نطاق',
    'Ext' => 'إكست',
    'Frnds/Usr' => 'فرندس / أسر',
    'Historical Datas' => 'داتاس التاريخية',
    'Historical Statistics' => 'الإحصاءات التاريخية',
    'ID' => 'هوية شخصية',
    'Inv>Org' => 'إنف> المؤسسة',
    'Is Social?' => 'هل اجتماعي؟',
    'Launches' => 'تطلق',
    'Level' => 'مستوى',
    'Meeting Planner' => 'مخطط لقاء',
    'Message ID' => 'معرف الرسالة',
    'Message Logs' => 'سجلات الرسائل',
    'Messages' => 'الرسائل',
    'Mtgs/Usr' => 'متس / أسر',
    'Places' => 'أماكن',
    'Plcs/Usr' => 'بلكس / أسر',
    'Reset' => 'إعادة تعيين',
    'Response' => 'استجابة',
    'Search' => 'بحث',
    'Sorry, we had a problem deleting your message.' => 'عذرا، حدثت مشكلة أثناء حذف رسالتك.',
    'Status' => 'الحالة',
    'Subject' => 'موضوع',
    'Target' => 'استهداف',
    'This message has been sent.' => 'تم إرسال هذه الرسالة.',
    'UId' => 'إيد',
    'Update' => 'تحديث',
    'Update {modelClass}: ' => 'تحديث {modelClass} :',
    'Updated At' => 'تم التحديث في',
    'User Data as of Yesterday' => 'بيانات المستخدم اعتبارا من يوم أمس',
    'User Datas' => 'دتس المستخدم',
    'User ID' => 'معرف المستخدم',
    'Users' => 'المستخدمون',
    'Your contacts have been imported.' => 'تم استيراد جهات الاتصال الخاصة بك.',
    'Your message has been deleted.' => 'تم حذف رسالتك.',
    'error!' => 'خطأ!',
    'ok' => 'حسنا',
    'one or more meetings not cleared_at in 24 hours' => 'ولم يتم إلغاء اجتماع واحد أو أكثر في غضون 24 ساعة',
    'ten recent meetings cleared_at = 0' => 'عشرة اجتماعات حديثة cleared_at = 0',
    'warn' => 'تحذير',
];