<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<سترونغ> ملاحظة: </ سترونغ> الرجاء استخدام متصفح محدث لعرض التعليقات.',
    'Download' => 'تحميل',
    'Follow' => 'إتبع',
    'Fork' => 'شوكة',
    'Issue' => 'القضية',
    'Login with Facebook' => 'تسجيل الدخول باستخدام الفيسبوك',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'الرجاء تمكين جافا سكريبت على المتصفح الخاص بك لعرض الفيسبوك {pluginName} المساعد بشكل صحيح على هذا الموقع.',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'الرجاء تمكين جافا سكريبت على المتصفح الخاص بك لعرض جوجل {pluginName} المساعد بشكل صحيح على هذا الموقع.',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'الرجاء تمكين جافا سكريبت على المتصفح الخاص بك لعرض تويتر {pluginName} المساعد بشكل صحيح على هذا الموقع.',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'الرجاء تمكين جافا سكريبت في المتصفح الخاص بك لعرض فكونتاكتي {pluginName} المساعد بشكل صحيح على هذا الموقع.',
    'Please enable JavaScript to view the {pluginLink}.' => 'الرجاء تمكين جافا سكريبت لعرض {pluginLink} .',
    'Star' => 'نجمة',
    'Watch' => 'راقب',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'يجب تمكين جافا سكريبت على متصفحك لكي يعمل الموقع على النحو الأمثل وعرض الأقسام تماما.',
    'comments powered by Disqus' => 'التعليقات مدعوم من ديسكس',
];