<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# Amigos',
    '# Mtgs' => 'Peldaños',
    '# Mtgs L30' => '# Mtgs L30',
    '# Places' => '# Lugares',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcpnt L30',
    '#FB' => '#PENSIÓN COMPLETA',
    '#Goog' => 'Gogo',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '% Reunión creada',
    '% Created Meeting Last30' => '% Creado Reunión Last30',
    '% Invited & Created Meeting' => '% De reuniones invitadas y creadas',
    '%Prtcpnt' => '% Prtcpnt',
    '%Prtcpnt L30' => '% Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'Una versión de prueba de esto se ha enviado a los administradores.',
    'Action Text' => 'Texto de la acción',
    'Action Url' => 'URL de acción',
    'Are you sure you want to delete this item?' => '¿Está seguro de que desea eliminar este elemento?',
    'Caption' => 'Subtítulo',
    'Content' => 'Contenido',
    'Create' => 'Crear',
    'Create Historical Data' => 'Crear datos históricos',
    'Create Launch' => 'Crear lanzamiento',
    'Create Message' => 'Crear un mensaje',
    'Create Message Log' => 'Crear registro de mensajes',
    'Create Place' => 'Crear lugar',
    'Create User' => 'Crear usuario',
    'Create User Data' => 'Crear datos de usuario',
    'Created At' => 'Creado en',
    'Date' => 'Fecha',
    'Delete' => 'Borrar',
    'Domain' => 'Dominio',
    'Ext' => 'Ext',
    'Frnds/Usr' => 'Frnds / Usr',
    'Historical Datas' => 'Datos históricos',
    'Historical Statistics' => 'Estadísticas históricas',
    'ID' => 'CARNÉ DE IDENTIDAD',
    'Inv>Org' => 'Inv> Org',
    'Is Social?' => '¿Es Social?',
    'Launches' => 'Lanza',
    'Level' => 'Nivel',
    'Meeting Planner' => 'Planificador de reuniones',
    'Message ID' => 'ID de mensaje',
    'Message Logs' => 'Registros de mensajes',
    'Messages' => 'Mensajes',
    'Mtgs/Usr' => 'Mtgs / Usr',
    'Places' => 'Lugares',
    'Plcs/Usr' => 'Plcs / Usr',
    'Reset' => 'Reiniciar',
    'Response' => 'Respuesta',
    'Search' => 'Buscar',
    'Sorry, we had a problem deleting your message.' => 'Lo sentimos, hemos tenido un problema al eliminar el mensaje.',
    'Status' => 'Estado',
    'Subject' => 'Tema',
    'Target' => 'Objetivo',
    'This message has been sent.' => 'Este mensaje se ha enviado.',
    'UId' => 'UID',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass} :',
    'Updated At' => 'Actualizado en',
    'User Data as of Yesterday' => 'Datos del usuario desde ayer',
    'User Datas' => 'Datos del usuario',
    'User ID' => 'Identidad de usuario',
    'Users' => 'Usuarios',
    'Your contacts have been imported.' => 'Se han importado tus contactos.',
    'Your message has been deleted.' => 'Su mensaje ha sido borrado.',
    'error!' => '¡error!',
    'ok' => 'De acuerdo',
    'one or more meetings not cleared_at in 24 hours' => 'Una o más reuniones no despejadas_ en 24 horas',
    'ten recent meetings cleared_at = 0' => 'Diez reuniones recientes cleared_at = 0',
    'warn' => 'advertir',
];