<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<Strong> Nota: </ strong> Utilice un navegador actualizado para ver los comentarios.',
    'Download' => 'Descargar',
    'Follow' => 'Seguir',
    'Fork' => 'Tenedor',
    'Issue' => 'Problema',
    'Login with Facebook' => 'Iniciar sesión con Facebook',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Por favor habilite JavaScript en su navegador para ver el Facebook {pluginName} Plugin correctamente en este sitio.',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Active JavaScript en su navegador para ver la página de Google {pluginName} Plugin correctamente en este sitio.',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'Activa JavaScript en tu navegador para ver el Twitter {pluginName} Plugin correctamente en este sitio.',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'Por favor active JavaScript en su navegador para ver el VKontakte {pluginName} Plugin correctamente en este sitio.',
    'Please enable JavaScript to view the {pluginLink}.' => 'Por favor, active JavaScript para ver el {pluginLink} .',
    'Star' => 'Estrella',
    'Watch' => 'Reloj',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'Debe habilitar Javascript en su navegador para que el sitio funcione de manera óptima y muestre las secciones por completo.',
    'comments powered by Disqus' => 'Comentarios impulsados ​​por Disqus',
];