<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '' => '',
    '# Friends' => '# Друзья',
    '# Mtgs' => '# Mtgs',
    '# Mtgs L30' => '# Mtgs L30',
    '# Places' => '# Места',
    '# Prtcpnt' => '# Prtcpnt',
    '# Prtcpnt L30' => '# Prtcpnt L30',
    '#FB' => '#FB',
    '#Goog' => '#Goog',
    '#LkIn' => '#LkIn',
    '#MComp' => '#MComp',
    '#MExp' => '#MExp',
    '#MPlan' => '#MPlan',
    '#Plcs' => '#Plcs',
    '#Usrs' => '#Usrs',
    '% Created Meeting' => '% Создано собрание',
    '% Created Meeting Last30' => '% Создано собрание Last30',
    '% Invited & Created Meeting' => '% Приглашенных и созданных собраний',
    '%Prtcpnt' => '% Prtcpnt',
    '%Prtcpnt L30' => '% Prtcpnt L30',
    'A test version of this has been sent to administrators.' => 'Тестовая версия этого была отправлена ​​администраторам.',
    'Action Text' => 'Текст действия',
    'Action Url' => 'URL-адрес действия',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Caption' => 'Подпись',
    'Content' => 'Содержание',
    'Create' => 'Создайте',
    'Create Historical Data' => 'Создание исторических данных',
    'Create Launch' => 'Создать запуск',
    'Create Message' => 'Создать сообщение',
    'Create Message Log' => 'Создать журнал сообщений',
    'Create Place' => 'Создать место',
    'Create User' => 'Создать пользователя',
    'Create User Data' => 'Создание пользовательских данных',
    'Created At' => 'Создан в',
    'Date' => 'Дата',
    'Delete' => 'Удалить',
    'Domain' => 'Домен',
    'Ext' => 'Ext',
    'Frnds/Usr' => 'Frnds / Usr',
    'Historical Datas' => 'Исторические данные',
    'Historical Statistics' => 'Историческая статистика',
    'ID' => 'Я БЫ',
    'Inv>Org' => 'Inv> Org',
    'Is Social?' => 'Социальный?',
    'Launches' => 'Запускает',
    'Level' => 'Уровень',
    'Meeting Planner' => 'Планировщик встреч',
    'Message ID' => 'Идентификатор сообщения',
    'Message Logs' => 'Журналы сообщений',
    'Messages' => 'Сообщения',
    'Mtgs/Usr' => 'Mtgs / Usr',
    'Places' => 'Места',
    'Plcs/Usr' => 'Plcs / Usr',
    'Reset' => 'Сброс',
    'Response' => 'отклик',
    'Search' => 'Поиск',
    'Sorry, we had a problem deleting your message.' => 'К сожалению, у нас возникла проблема с удалением вашего сообщения.',
    'Status' => 'Положение дел',
    'Subject' => 'Предмет',
    'Target' => 'Цель',
    'This message has been sent.' => 'Это сообщение отправлено.',
    'UId' => 'UId',
    'Update' => 'Обновить',
    'Update {modelClass}: ' => 'Обновить {modelClass} :',
    'Updated At' => 'Обновлено: At',
    'User Data as of Yesterday' => 'Данные пользователя на вчера',
    'User Datas' => 'Данные пользователя',
    'User ID' => 'Идентификатор пользователя',
    'Users' => 'Пользователи',
    'Your contacts have been imported.' => 'Контакты импортированы.',
    'Your message has been deleted.' => 'Ваше сообщение было удалено.',
    'error!' => 'ошибка!',
    'ok' => 'ОК',
    'one or more meetings not cleared_at in 24 hours' => 'Одна или несколько встреч не очищаются в течение 24 часов',
    'ten recent meetings cleared_at = 0' => 'Десять последних встреч cleared_at = 0',
    'warn' => 'Предупредить',
];