<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    '<strong>Note:</strong> Please use an updated browser to view comments.' => '<Strong> Примечание. </ Strong> Для просмотра комментариев используйте обновленный браузер.',
    'Download' => 'Скачать',
    'Follow' => 'следить',
    'Fork' => 'вилка',
    'Issue' => 'вопрос',
    'Login with Facebook' => 'Войти с Facebook',
    'Please enable JavaScript on your browser to view the Facebook {pluginName} plugin correctly on this site.' => 'Пожалуйста, включите JavaScript в своем браузере для просмотра в Facebook {pluginName} Плагин правильно на этом сайте.',
    'Please enable JavaScript on your browser to view the Google {pluginName} plugin correctly on this site.' => 'Пожалуйста, включите JavaScript в вашем браузере для просмотра Google {pluginName} Плагин правильно на этом сайте.',
    'Please enable JavaScript on your browser to view the Twitter {pluginName} plugin correctly on this site.' => 'Включите JavaScript в своем браузере для просмотра Twitter {pluginName} Плагин правильно на этом сайте.',
    'Please enable JavaScript on your browser to view the VKontakte {pluginName} plugin correctly on this site.' => 'Включите JavaScript в своем браузере для просмотра ВКонтакте {pluginName} Плагин правильно на этом сайте.',
    'Please enable JavaScript to view the {pluginLink}.' => 'Пожалуйста, включите JavaScript для просмотра {pluginLink} ,',
    'Star' => 'звезда',
    'Watch' => 'Смотреть',
    'You must enable Javascript on your browser for the site to work optimally and display sections completely.' => 'Вы должны включить Javascript в своем браузере, чтобы сайт работал оптимально и отображал разделы полностью.',
    'comments powered by Disqus' => 'Яндекс цитирования',
];